# Import Libraries

In [34]:
import os
import pickle
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics import classification_report

# Set Parameters

In [35]:
dataset_nr = 2
assert dataset_nr == 1 or 2

disease_prefix = 'hd'
assert disease_prefix == 'dmd' or 'hd'

embedding_method = 'e2v'
assert embedding_method == 'e2v' or 'm2v'

# Additional experiments
NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = None  # set to None when no conceptual changes are wanted

if concept_changes:
    concept_changes_str = concept_changes
else:
    concept_changes_str = ''
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''

seeded_emb = False

if seeded_emb:
    fixed_emb = '_seeded'
else:
    fixed_emb = ''
    
if seeded_emb:
    title_seeded = ' with fixed node embeddings'
else:
    title_seeded = ''

# Get Result Paths

In [36]:
curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)
dataset_output_dir = os.path.join(curr_output_dir, f'g{dataset_nr}_{embedding_method}{fixed_emb}{suffix}')

if not os.path.exists(dataset_output_dir):
    print('First, run the edge2vec embedding script. Then, run this script.')
else:
    print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {dataset_output_dir}')
    
run_folders_list = []
for item in os.listdir(dataset_output_dir):
    curr_path = os.path.join(dataset_output_dir, item)
    if os.path.isdir(curr_path) and 'run' in item:
        run_folders_list.append(item)

print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

run_folders_paths = []
pred_folders_paths = []
for run_folder in run_folders_list:
    run_path = os.path.join(dataset_output_dir, run_folder)
    run_folders_paths.append(run_path)
    pred_run_path = os.path.join(run_path, 'pred')
    pred_folders_paths.append(pred_run_path)
    print(pred_run_path)

Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v
A total of 10 runs will be included in the analysis.
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_001\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_002\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_003\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_004\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_005\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_006\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_007\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_008\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_009\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v\run_010\pred

In [37]:
auc_scores_all_runs = []
auc_loss_scores_all_runs = []

for run_name, pred_folder in zip(run_folders_list, pred_folders_paths):
    with open(f'{pred_folder}/performance_scores_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_info = pickle.load(f)
        
    keys = ['AUC Train', 'AUC Validation', 'AUC Test']
    for key in keys:
        auc_scores = loaded_info[key]
        for index, auc_score in enumerate(auc_scores):
            auc_scores_per_run = {'run': run_name, 'name': key, 'iteration': index, 'score': auc_score}
            auc_scores_all_runs.append(auc_scores_per_run)
            auc_loss_scores_all_runs.append(auc_scores_per_run)

    loss_scores = loaded_info['Loss']
    for index, loss_score in enumerate(loss_scores):
        formatted_loss_score = float(np.log10(loss_score))
        loss_scores_per_run = {'run': run_name, 'name': 'Cross-Entropy Loss', 'iteration': index, 'score': formatted_loss_score}
        auc_loss_scores_all_runs.append(loss_scores_per_run)

# Plot ROC Curves, AUC-ROC Scores and F1 Scores for Each Model

## ROC Curves

In [38]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)

final_test_auc_roc_scores_all_runs_all_models = []
roc_curve_all_runs_all_models = []
f1_scores_all_runs_all_models = []

for setting in all_settings:
    curr_dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(curr_dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {curr_dataset_output_dir}')
            
        run_folders_list = []
        for item in os.listdir(curr_dataset_output_dir):
            curr_path = os.path.join(curr_dataset_output_dir, item)
            if os.path.isdir(curr_path) and 'run' in item:
                run_folders_list.append(item)

        print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

        run_folders_paths = []
        curr_pred_folders_paths = []
        for run_folder in run_folders_list:
            run_path = os.path.join(curr_dataset_output_dir, run_folder)
            run_folders_paths.append(run_path)
            pred_run_path = os.path.join(run_path, 'pred')
            curr_pred_folders_paths.append(pred_run_path)
            
        for run_name, pred_folder in zip(run_folders_list, curr_pred_folders_paths):
            with open(f'{pred_folder}/performance_scores_{setting["dataset_nr"]}_{setting["embedding_method"]}.pkl', 'rb') as f:
                loaded_info = pickle.load(f)

            auc_roc_score = loaded_info['ROC AUC Score']
            formatted_auc_roc_score = float(auc_roc_score)
            auc_roc_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                        'ROC AUC Score': formatted_auc_roc_score}
            final_test_auc_roc_scores_all_runs_all_models.append(auc_roc_score_per_run)

            roc_fpr_scores = loaded_info['ROC FPR']
            roc_tpr_scores = loaded_info['ROC TPR']
            
            for fpr, tpr in zip(roc_fpr_scores, roc_tpr_scores):
                auc_per_threshold_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}',
                                             'ROC FPR': fpr, 'ROC TPR': tpr}
                roc_curve_all_runs_all_models.append(auc_per_threshold_per_run)

            f1_score = loaded_info['F1 Score']
            formatted_f1_score = float(f1_score)
            f1_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                'F1 Score': formatted_f1_score}
            f1_scores_all_runs_all_models.append(f1_score_per_run)

            print(f'F1-Score in the test set of dataset {setting["dataset_nr"]} and method {setting["embedding_method"]}:', f1_score)
            print(classification_report(loaded_info['True Labels'], loaded_info['Predicted Labels']))

Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v
A total of 10 runs will be included in the analysis.
F1-Score in the test set of dataset 1 and method e2v: 0.9486849708289065
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9486882860021644
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.21129471099608466
              precision    recall  f1-score   support

           0       0.36      1.00      0.53     13476
           1       1.00      0.12      0.21     26952

    accuracy                           0.41     40428
   macro avg       0.68      0.56      0.37     40428
weighted avg       0.79      0.41      0.32     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9514784068650312
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.96      0.95      0.95     26952

    accuracy                           0.94     40428
   macro avg       0.93      0.93      0.93     40428
weighted avg       0.94      0.94      0.94     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9492572875172183
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9486486989886196
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9487212967971795
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9485318745115551
              precision    recall  f1-score   support

           0       0.89      0.90      0.90     13476
           1       0.95      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.92      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9493545923594167
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9478945209055986
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.92      0.92     40428
weighted avg       0.93      0.93      0.93     40428

Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v
A total of 10 runs will be included in the analysis.
F1-Score in the test set of dataset 2 and method e2v: 0.8931073895542414
              precision    recall  f1-score   support

           0       0.97      0.54      0.70     13600
           1       0.81      0.99      0.89     27200

    accuracy                           0.84     40800
   macro avg       0.89      0.77      0.79     40800
weighted avg       0.86      0.84      0.83     40800

F1-Score in the test set of dataset 2 and method e2v: 0.880600172500773
              precision    recall  f1-score   support

           0       0.98      0.47      0.64     13600
           1       0.79      0.99      0.88     27200

    accuracy                           0.82     40800
   macro avg       0.88      0.73      0.76     40800
weighted avg       0.85      0.82      0.80     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8845057501392484
              precision    recall  f1-score   support

           0       0.97      0.50      0.66     13600
           1       0.80      0.99      0.88     27200

    accuracy                           0.83     40800
   macro avg       0.88      0.74      0.77     40800
weighted avg       0.86      0.83      0.81     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8945414592731934
              precision    recall  f1-score   support

           0       0.96      0.56      0.71     13600
           1       0.82      0.99      0.89     27200

    accuracy                           0.84     40800
   macro avg       0.89      0.77      0.80     40800
weighted avg       0.86      0.84      0.83     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8808365996064208
              precision    recall  f1-score   support

           0       0.98      0.47      0.64     13600
           1       0.79      1.00      0.88     27200

    accuracy                           0.82     40800
   macro avg       0.89      0.73      0.76     40800
weighted avg       0.85      0.82      0.80     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8768552725387257
              precision    recall  f1-score   support

           0       0.98      0.45      0.62     13600
           1       0.78      0.99      0.88     27200

    accuracy                           0.81     40800
   macro avg       0.88      0.72      0.75     40800
weighted avg       0.85      0.81      0.79     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8657450272979791
              precision    recall  f1-score   support

           0       0.98      0.39      0.56     13600
           1       0.77      1.00      0.87     27200

    accuracy                           0.79     40800
   macro avg       0.87      0.69      0.71     40800
weighted avg       0.84      0.79      0.76     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8935951951554459
              precision    recall  f1-score   support

           0       0.97      0.54      0.70     13600
           1       0.81      0.99      0.89     27200

    accuracy                           0.84     40800
   macro avg       0.89      0.77      0.79     40800
weighted avg       0.87      0.84      0.83     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8854906722234073
              precision    recall  f1-score   support

           0       0.97      0.50      0.66     13600
           1       0.80      0.99      0.89     27200

    accuracy                           0.83     40800
   macro avg       0.88      0.75      0.77     40800
weighted avg       0.86      0.83      0.81     40800

F1-Score in the test set of dataset 2 and method e2v: 0.8894962133684557
              precision    recall  f1-score   support

           0       0.97      0.52      0.68     13600
           1       0.81      0.99      0.89     27200

    accuracy                           0.84     40800
   macro avg       0.89      0.76      0.78     40800
weighted avg       0.86      0.84      0.82     40800

In [39]:
roc_curve_all_runs_all_models = pd.DataFrame(roc_curve_all_runs_all_models)
roc_curve_all_runs_all_models

        Model   ROC FPR   ROC TPR
0      g1_e2v  0.000000  0.000000
1      g1_e2v  0.000000  0.001781
2      g1_e2v  0.000000  0.002671
3      g1_e2v  0.000000  0.003710
4      g1_e2v  0.000000  0.003933
...       ...       ...       ...
75719  g2_e2v  0.950074  0.999853
75720  g2_e2v  0.950074  0.999926
75721  g2_e2v  0.986103  0.999926
75722  g2_e2v  0.986103  1.000000
75723  g2_e2v  1.000000  1.000000

[75724 rows x 3 columns]

In [40]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'ROC TPR/ROC FPR Distribution over Each Run for Each Model')
sns.scatterplot(data=roc_curve_all_runs_all_models, x="ROC FPR", y="ROC TPR", hue="Model", s=1)
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.legend(markerscale=10)

fig.savefig(f'{curr_output_dir}/roc_curves.png', bbox_inches='tight')
fig.clear()

## F1 Scores

In [41]:
f1_scores_all_runs_all_models = pd.DataFrame(f1_scores_all_runs_all_models)
f1_scores_all_runs_all_models

     Model  F1 Score
0   g1_e2v  0.948685
1   g1_e2v  0.948688
2   g1_e2v  0.211295
3   g1_e2v  0.951478
4   g1_e2v  0.949257
5   g1_e2v  0.948649
6   g1_e2v  0.948721
7   g1_e2v  0.948532
8   g1_e2v  0.949355
9   g1_e2v  0.947895
10  g2_e2v  0.893107
11  g2_e2v  0.880600
12  g2_e2v  0.884506
13  g2_e2v  0.894541
14  g2_e2v  0.880837
15  g2_e2v  0.876855
16  g2_e2v  0.865745
17  g2_e2v  0.893595
18  g2_e2v  0.885491
19  g2_e2v  0.889496

In [42]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'F1 Scores Overview for Each Model')
sns.barplot(f1_scores_all_runs_all_models, x="Model", y="F1 Score", errorbar="sd", color='cornflowerblue')
ax.bar_label(ax.containers[0], fontsize=10, padding=5)
ax.set_xlabel('Model Variant')
ax.set_ylabel('F1 Score')

fig.savefig(f'{curr_output_dir}/f1_scores.png', bbox_inches='tight')
fig.clear()

## Final AUC-ROC Scores

In [43]:
final_test_auc_roc_scores_all_runs_all_models = pd.DataFrame(final_test_auc_roc_scores_all_runs_all_models)
final_test_auc_roc_scores_all_runs_all_models

     Model  ROC AUC Score
0   g1_e2v       0.960639
1   g1_e2v       0.963632
2   g1_e2v       0.964462
3   g1_e2v       0.964454
4   g1_e2v       0.962858
5   g1_e2v       0.964652
6   g1_e2v       0.962713
7   g1_e2v       0.963199
8   g1_e2v       0.962839
9   g1_e2v       0.962624
10  g2_e2v       0.970630
11  g2_e2v       0.973433
12  g2_e2v       0.970901
13  g2_e2v       0.968553
14  g2_e2v       0.972734
15  g2_e2v       0.971305
16  g2_e2v       0.972849
17  g2_e2v       0.973146
18  g2_e2v       0.970236
19  g2_e2v       0.970900

In [44]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'AUC-ROC Scores Overview for Each Model')
sns.barplot(final_test_auc_roc_scores_all_runs_all_models, x="Model", y="ROC AUC Score", errorbar="sd")
ax.bar_label(ax.containers[0], fontsize=10, padding=10)
ax.set_ylim(0.85,1) # 0.85, 1
ax.set_xlabel('Model Variant')
ax.set_ylabel('AUC-ROC Score')

fig.savefig(f'{curr_output_dir}/auc_roc_scores.png', bbox_inches='tight')
fig.clear()

# Plot Training Curve

In [45]:
auc_scores_all_runs = pd.DataFrame(auc_scores_all_runs)
auc_scores_all_runs

          run       name  iteration     score
0     run_001  AUC Train          0  0.982114
1     run_001  AUC Train          1  0.980495
2     run_001  AUC Train          2  0.979732
3     run_001  AUC Train          3  0.977543
4     run_001  AUC Train          4  0.976246
...       ...        ...        ...       ...
2965  run_010   AUC Test         94  0.966948
2966  run_010   AUC Test         95  0.967150
2967  run_010   AUC Test         96  0.967304
2968  run_010   AUC Test         97  0.967490
2969  run_010   AUC Test         98  0.967661

[2970 rows x 4 columns]

In [46]:
auc_loss_scores_all_runs = pd.DataFrame(auc_loss_scores_all_runs)
auc_loss_scores_all_runs

          run                name  iteration     score
0     run_001           AUC Train          0  0.982114
1     run_001           AUC Train          1  0.980495
2     run_001           AUC Train          2  0.979732
3     run_001           AUC Train          3  0.977543
4     run_001           AUC Train          4  0.976246
...       ...                 ...        ...       ...
3955  run_010  Cross-Entropy Loss         94 -0.292116
3956  run_010  Cross-Entropy Loss         95 -0.291096
3957  run_010  Cross-Entropy Loss         96 -0.296897
3958  run_010  Cross-Entropy Loss         97 -0.302488
3959  run_010  Cross-Entropy Loss         98 -0.303413

[3960 rows x 4 columns]

In [47]:
fig, ax = plt.subplots(figsize=(8, 8))

ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(0.8,1) # 0.85, 1
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC Score')

print(dataset_output_dir)
fig.savefig(f'{dataset_output_dir}/training_curve.png', bbox_inches='tight')
fig.clear()

c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v

In [48]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_loss_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(top=1)
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC/log10(Loss)')

fig.savefig(f'{dataset_output_dir}/training_curve_with_loss.png', bbox_inches='tight')
fig.clear()

# Similarity between top scoring symptom-drug pairs

In [49]:
drug_symptom_pairs_per_run = []

for index, pred_path in enumerate(pred_folders_paths):
    with open(f'{pred_path}/candidates_per_symptom_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_list = pickle.load(f)
        
        drug_symptom_pairs = []
        
        for _, row in loaded_list.iterrows():
            symptom_id = row['Symptom']
            candidates = row['Candidates']
            
            for candidate in candidates:
                drug_symptom_pairs.append(tuple([symptom_id, candidate]))
                
        total_drug_symptom_pairs = len(drug_symptom_pairs)
    
    drug_symptom_pairs_per_run.append(drug_symptom_pairs)

In [50]:
similarity_matrix = {}
ratios_non_diagonals = []

for index1, pairs1 in enumerate(drug_symptom_pairs_per_run):
    
    similarities = {}
    
    for index2, pairs2 in enumerate(drug_symptom_pairs_per_run):
        overlap = set([tuple(sorted(ele)) for ele in pairs1]) & set([tuple(sorted(ele)) for ele in pairs2])
        ratio_overlap = len(overlap) / total_drug_symptom_pairs * 100
        
        similarities[f'run {index2+1}'] = ratio_overlap
        
        if index1 != index2:
            ratios_non_diagonals.append(ratio_overlap)
        
    similarity_matrix[f'run {index1+1}'] = similarities
    
similarity_matrix_df = pd.DataFrame(similarity_matrix)
similarity_matrix_df

,run 1,run 2,run 3,run 4,run 5,run 6,run 7,run 8,run 9,run 10
run 1,100.000000,28.735632,21.839080,22.988506,12.643678,20.114943,25.287356,33.333333,25.862069,24.712644
run 2,28.735632,100.000000,21.839080,34.482759,20.114943,12.068966,25.287356,33.908046,20.689655,32.183908
run 3,21.839080,21.839080,100.000000,13.218391,22.413793,14.942529,10.344828,14.942529,17.816092,29.885057
run 4,22.988506,34.482759,13.218391,100.000000,16.666667,17.816092,21.264368,17.816092,23.563218,28.735632
run 5,12.643678,20.114943,22.413793,16.666667,100.000000,15.517241,11.494253,14.942529,13.793103,21.839080
run 6,20.114943,12.068966,14.942529,17.816092,15.517241,100.000000,14.942529,20.114943,26.436782,15.517241
run 7,25.287356,25.287356,10.344828,21.264368,11.494253,14.942529,100.000000,21.264368,18.390805,17.816092
run 8,33.333333,33.908046,14.942529,17.816092,14.942529,20.114943,21.264368,100.000000,25.862069,26.436782
run 9,25.862069,20.689655,17.816092,23.563218,13.793103,26.436782,18.390805,25.862069,100.000000,28.160920
run 10,24.712644,32.183908,29.885057,28.735632,21.839080,15.517241,17.816092,26.436782,28.160920,100.000000

In [51]:
mean_overlap_ratio = np.mean(ratios_non_diagonals)
median_overlap_ratio = np.median(ratios_non_diagonals)
print('Mean:', mean_overlap_ratio)
print('Median:', median_overlap_ratio)

Mean: 21.289910600255425
Median: 21.26436781609195

In [52]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Overlap ratio (Mean: {round(mean_overlap_ratio, 2)}, Median: {round(median_overlap_ratio, 2)}) between list of predicted symptom-drug pairs per run on dataset {dataset_nr} {concept_changes_str}')
sns.heatmap(similarity_matrix_df, annot=True, fmt='.1f', linewidths=0.5, ax=ax, cmap='RdYlGn')
ax.collections[0].set_clim(0,100)

fig.savefig(f'{dataset_output_dir}/overlap_between_runs.png', bbox_inches='tight')
fig.clear()

In [53]:
for i in range(0, len(drug_symptom_pairs_per_run)):
    if i == 0:
        overlapping_pairs_all_runs = set(drug_symptom_pairs_per_run[i])
    else:
        overlapping_pairs_all_runs = overlapping_pairs_all_runs & set(drug_symptom_pairs_per_run[i])
            
print(f'There are {len(overlapping_pairs_all_runs)} symptom-drug pairs that are found in the top list of drug candidates in {len(drug_symptom_pairs_per_run)} runs: \n {overlapping_pairs_all_runs}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{dataset_nr}_{embedding_method}{fixed_emb}.pkl', 'wb') as f:
    pickle.dump(overlapping_pairs_all_runs, f)

There are 1 symptom-drug pairs that are found in the top list of drug candidates in 10 runs:
 {('HP:0000741', '5359')}

In [55]:
same_drug_symptom_pairs_thresholded = set()

threshold = 0.5
total_runs = len(drug_symptom_pairs_per_run)
min_nr_runs = int(threshold * total_runs)

for i in range(0, len(drug_symptom_pairs_per_run)):
    for pair in drug_symptom_pairs_per_run[i]:
        same_pairs = 0
        for j in range(0, len(drug_symptom_pairs_per_run)):
            for pair_to_compare in drug_symptom_pairs_per_run[j]:
                if pair == pair_to_compare:
                    same_pairs += 1
                        
        #print(f'For pair {pair} from run {i}, there are {same_pairs} same pairs found in list of all runs.')
        if same_pairs >= min_nr_runs:
            same_drug_symptom_pairs_thresholded.add(pair)
            
print(f'There are {len(same_drug_symptom_pairs_thresholded)} symptom-drug pairs that are found in the top list of drug candidates in at least {min_nr_runs} of the {total_runs} runs: \n {same_drug_symptom_pairs_thresholded}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_{min_nr_runs}_runs_{dataset_nr}_{embedding_method}{fixed_emb}{suffix}.pkl', 'wb') as f:
    pickle.dump(same_drug_symptom_pairs_thresholded, f)

There are 76 symptom-drug pairs that are found in the top list of drug candidates in at least 5 of the 10 runs:
 {('HP:0025401', '578'), ('HP:0000496', '2123'), ('HP:0010794', '2123'), ('HP:0030955', '2123'), ('HP:0000739', '5359'), ('HP:0031843', '2123'), ('HP:0003107', '2123'), ('HP:0002355', '5359'), ('HP:0031589', '2123'), ('HP:0031473', '578'), ('HP:0000741', '578'), ('HP:0000734', '5359'), ('HP:0002141', '5359'), ('HP:0002312', '5359'), ('HP:0009088', '578'), ('HP:0001824', '1996'), ('HP:0007010', '2123'), ('HP:0000734', '2123'), ('HP:0002141', '2123'), ('HP:0002340', '2123'), ('HP:0002312', '2123'), ('HP:0100785', '578'), ('HP:0030955', '578'), ('HP:0001347', '2123'), ('HP:0002063', '5359'), ('HP:0001347', '5359'), ('HP:0003107', '578'), ('HP:0004305', '4360'), ('HP:0031843', '578'), ('HP:0000713', '5359'), ('HP:0000716', '5359'), ('HP:0002063', '3082'), ('HP:0031589', '578'), ('HP:0004305', '3082'), ('HP:0000746', '5359'), ('HP:0000713', '2123'), ('HP:0002066', '2123'), ('HP:0007010', '578'), ('HP:0002171', '5359'), ('HP:0001288', '5359'), ('HP:0002141', '578'), ('HP:0030842', '2123'), ('HP:0000746', '2123'), ('HP:0002529', '5359'), ('HP:0002169', '2123'), ('HP:0000738', '5359'), ('HP:0000751', '5359'), ('HP:0200136', '1679'), ('HP:0002354', '2123'), ('HP:0002354', '5359'), ('HP:0031845', '2123'), ('HP:0002067', '5359'), ('HP:0000713', '578'), ('HP:0001332', '5359'), ('HP:0000718', '4360'), ('HP:0001268', '4360'), ('HP:0001288', '578'), ('HP:0045082', '2123'), ('HP:0002540', '2286'), ('HP:0002171', '578'), ('HP:0002300', '5359'), ('HP:0001262', '2525'), ('HP:0000751', '578'), ('HP:0030842', '578'), ('HP:0000741', '5359'), ('HP:0000718', '3082'), ('HP:0000726', '5359'), ('HP:0009088', '2123'), ('HP:0031845', '578'), ('HP:0001272', '1310'), ('HP:0000737', '2123'), ('HP:0003324', '5359'), ('HP:0000737', '5359'), ('HP:0003487', '5359'), ('HP:0003324', '2123'), ('HP:0003487', '2123')}

# Symptoms related to DMD

In [56]:
edges = pd.read_csv(f'output/{disease_prefix}/indexed_edges_{dataset_nr}{suffix}.csv')
edges

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0000774,gametogenesis variant,8,9968,0
1,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0002188,male somatic gonad development variant,8,3292,0
2,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001224,axon outgrowth variant,8,8349,0
3,WormBase:WBGene00006537,tbb-2,4,10272,in orthology relationship with,MGI:107812,Tubb5,4,4998,1
4,WormBase:WBGene00006537,tbb-2,4,10272,causes condition,WBPhenotype:0001100,early embryonic lethal,8,6541,0
...,...,...,...,...,...,...,...,...,...,...
230223,Q99460,26S proteasome non-ATPase regulatory subunit 1,5,4895,is product of,HGNC:9554,PSMD1,4,352,11
230224,P53396,ATP-citrate synthase,5,1449,is product of,HGNC:115,ACLY,4,10260,11
230225,Q60631,Growth factor receptor-bound protein 2,5,12956,is product of,MGI:95805,Grb2,4,6661,11
230226,1980,octreotide,3,5596,targets,P35372,Mu-type opioid receptor,5,6566,12
230227,P00533,Epidermal growth factor receptor,5,6337,is product of,HGNC:3236,EGFR,4,8284,11

In [57]:
if dataset_nr == 1:
    pheno_rel = 'has phenotype'
else:
    pheno_rel = 'associated with phenotype'
    
_, relation_labels = pd.factorize(edges['relation'])

if disease_prefix == 'dmd':
    disease_ID = 'MONDO:0010679'
elif disease_prefix == 'hd':
    disease_ID = 'MONDO:0007739'
    
relation_index = list(relation_labels).index(pheno_rel)

symptoms = edges[(edges['head'] == disease_ID) & (edges['type'] == relation_index)]

print(f'A total of {symptoms.shape[0]} symptoms found that are associated with {disease_ID}')
symptoms

A total of 58 symptoms found that are associated with MONDO:0007739

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
146365,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000741,Apathy,8,4744,16
146366,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002072,Chorea,8,4602,16
146367,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000739,Anxiety,8,379,16
146368,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001268,Mental deterioration,8,14797,16
146369,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0031843,Bradyphrenia,8,1275,16
146370,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001336,Myoclonus,8,2811,16
146371,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0030842,Choking episodes,8,11918,16
146372,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0030955,Alcoholism,8,2007,16
146373,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000738,Hallucinations,8,9906,16
146374,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0040140,Degeneration of the striatum,8,6365,16
146375,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0031589,Suicidal ideation,8,2147,16
146376,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0031845,Abnormal libido,8,11270,16
146377,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002591,Polyphagia,8,9372,16
146378,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002529,Neuronal loss in central nervous system,8,8063,16
146379,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002354,Memory impairment,8,3630,16
146380,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000716,Depression,8,9167,16
146381,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001824,Weight loss,8,7475,16
146382,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002063,Rigidity,8,8027,16
146383,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002312,Clumsiness,8,8495,16
146384,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000746,Delusions,8,7134,16
146385,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001288,Gait disturbance,8,4699,16
146386,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000726,Dementia,8,2964,16
146387,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002340,Caudate atrophy,8,11961,16
146388,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002141,Gait imbalance,8,14038,16
146389,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002059,Cerebral atrophy,8,3878,16
146390,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000722,Obsessive-compulsive behavior,8,13306,16
146391,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002171,Gliosis,8,4439,16
146392,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000734,Disinhibition,8,13831,16
146393,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002355,Difficulty walking,8,677,16
146394,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0003487,Babinski sign,8,4831,16
146395,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001262,Excessive daytime somnolence,8,10750,16
146397,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0004305,Involuntary movements,8,10827,16
146398,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000751,Personality changes,8,2372,16
146399,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0004408,Abnormality of the sense of smell,8,14390,16
146400,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001332,Dystonia,8,8622,16
146401,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0010794,Impaired visuospatial constructive cognition,8,2451,16
146402,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002500,Abnormal cerebral white matter morphology,8,14520,16
146403,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002067,Bradykinesia,8,1312,16
146404,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0007010,Poor fine motor coordination,8,5318,16
146405,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000713,Agitation,8,8962,16
146406,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002300,Mutism,8,11200,16
146407,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0025401,Staring gaze,8,5521,16
146408,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001272,Cerebellar atrophy,8,9434,16
146409,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0009088,Speech articulation difficulties,8,2612,16
146410,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0031473,Hostility,8,6734,16
146411,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0200136,Oral-pharyngeal dysphagia,8,6215,16
146412,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0003107,Abnormal circulating cholesterol concentration,8,13454,16
146413,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0100785,Insomnia,8,1992,16
146414,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002066,Gait ataxia,8,12492,16
146415,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000496,Abnormality of eye movement,8,3232,16
146416,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001347,Hyperreflexia,8,11744,16
146417,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0045082,Decreased body mass index,8,8352,16
146418,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000718,Aggressive behavior,8,11246,16
146419,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0003324,Generalized muscle weakness,8,303,16
146420,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002540,Inability to walk,8,13553,16
146421,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0002169,Clonus,8,10729,16
146422,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0001250,Seizure,8,3724,16
146423,MONDO:0007739,Huntington disease,2,5948,associated with phenotype,HP:0000737,Irritability,8,6133,16

In [58]:
symptoms_df = symptoms[['tail', 'label_tail']]
symptoms_df = symptoms_df.rename(columns={'tail': 'Symptom ID', 'label_tail': 'Symptom'})
symptoms_df.to_csv(f'{curr_output_dir}/{disease_prefix}relatedsymptoms.csv', index=False)

# Check overlap between each model

In [59]:
nodes = pd.read_csv(f'output/{disease_prefix}/indexed_nodes_{dataset_nr}.csv')
nodes.drop('index_id', axis=1, inplace=True)
nodes['semantic'] = nodes['semantic'].astype('category')
nodes

,id,semantic,label,semantic_id
0,dictyBase:DDB_G0282941,gene,DDB0185273,4
1,WBPhenotype:0001133,phenotype,division axis defective,8
2,HP:0012005,phenotype,Deja vu aura,8
3,ENSEMBL:ENSPTRG00000043959,gene,ENSEMBL:ENSPTRG00000043959,4
4,HP:0001265,phenotype,Hyporeflexia,8
...,...,...,...,...
14877,MGI:2676637,gene,H2-M11,4
14878,MP:0000378,phenotype,absent hair follicles,8
14879,WormBase:WBGene00006446,gene,atx-3,4
14880,MGI:2654144,gene,Ercc6l,4
14881,1912,drug,niclosamide,3

In [60]:
if dataset_nr == 1:
    drug_semantic = 'DRUG'
else:
    drug_semantic = 'drug'

nodes[nodes['semantic'] == drug_semantic]

         id semantic               label  semantic_id
204    2632     drug         thioguanine            3
249    2650     drug          tianeptine            3
281     844     drug  dextropropoxyphene            3
371    2832     drug            thiamine            3
383    2459     drug           sorafenib            3
...     ...      ...                 ...          ...
14313  1800     drug          miconazole            3
14510   143     drug           alvimopan            3
14629  2491     drug          sufentanil            3
14840  2422     drug          saquinavir            3
14881  1912     drug         niclosamide            3

[215 rows x 4 columns]

In [61]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)

overlapping_pairs = []

for setting in all_settings:
    dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {setting["dataset_nr"]} exists and will be loaded: {dataset_output_dir}')
        
        with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}.pkl', 'rb') as f:
            loaded_list = pickle.load(f)
            overlapping_pairs.append(loaded_list)
            
            pair_dict_list = []
            for pair in loaded_list:
                symptom_id, drug_id = pair
                
                symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
                
                drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
                pair_dict_list.append({'Drug': drug_name, 'Symptom ID': symptom_id, 'Symptom': symptom_name})
                
            overlapping_all_runs_df = pd.DataFrame(pair_dict_list)
            overlapping_all_runs_df.to_csv(f'{dataset_output_dir}/symptom_drug_pairs_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}.csv', index=False)

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v
Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g2_e2v

In [62]:
dataset1_emb_overlap = overlapping_pairs[0].intersection(overlapping_pairs[1])
for pair in dataset1_emb_overlap:
    symptom_id, drug_id = pair
    symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
    drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
    print(drug_name, 'treats', symptom_name)