# Import Libraries

In [1]:
import os
import pickle
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics import classification_report

# Set Parameters

In [2]:
dataset_nr = 1
assert dataset_nr == 1 or 2

disease_prefix = 'hd'
assert disease_prefix == 'dmd' or 'hd'

embedding_method = 'e2v'
assert embedding_method == 'e2v' or 'm2v'

# Additional experiments
NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = None  # set to None when no conceptual changes are wanted

if concept_changes:
    concept_changes_str = concept_changes
else:
    concept_changes_str = ''
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''

seeded_emb = False

if seeded_emb:
    fixed_emb = '_seeded'
else:
    fixed_emb = ''
    
if seeded_emb:
    title_seeded = ' with fixed node embeddings'
else:
    title_seeded = ''

# Get Result Paths

In [3]:
curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)
dataset_output_dir = os.path.join(curr_output_dir, f'g{dataset_nr}_{embedding_method}{fixed_emb}{suffix}')

if not os.path.exists(dataset_output_dir):
    print('First, run the edge2vec embedding script. Then, run this script.')
else:
    print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {dataset_output_dir}')
    
run_folders_list = []
for item in os.listdir(dataset_output_dir):
    curr_path = os.path.join(dataset_output_dir, item)
    if os.path.isdir(curr_path) and 'run' in item:
        run_folders_list.append(item)

print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

run_folders_paths = []
pred_folders_paths = []
for run_folder in run_folders_list:
    run_path = os.path.join(dataset_output_dir, run_folder)
    run_folders_paths.append(run_path)
    pred_run_path = os.path.join(run_path, 'pred')
    pred_folders_paths.append(pred_run_path)
    print(pred_run_path)

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v
A total of 10 runs will be included in the analysis.
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_001\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_002\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_003\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_004\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_005\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_006\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_007\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_008\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_009\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v\run_010\pred

In [4]:
auc_scores_all_runs = []
auc_loss_scores_all_runs = []

for run_name, pred_folder in zip(run_folders_list, pred_folders_paths):
    with open(f'{pred_folder}/performance_scores_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_info = pickle.load(f)
        
    keys = ['AUC Train', 'AUC Validation', 'AUC Test']
    for key in keys:
        auc_scores = loaded_info[key]
        for index, auc_score in enumerate(auc_scores):
            auc_scores_per_run = {'run': run_name, 'name': key, 'iteration': index, 'score': auc_score}
            auc_scores_all_runs.append(auc_scores_per_run)
            auc_loss_scores_all_runs.append(auc_scores_per_run)

    loss_scores = loaded_info['Loss']
    for index, loss_score in enumerate(loss_scores):
        formatted_loss_score = float(np.log10(loss_score))
        loss_scores_per_run = {'run': run_name, 'name': 'Cross-Entropy Loss', 'iteration': index, 'score': formatted_loss_score}
        auc_loss_scores_all_runs.append(loss_scores_per_run)

# Plot ROC Curves, AUC-ROC Scores and F1 Scores for Each Model

## ROC Curves

In [5]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)

final_test_auc_roc_scores_all_runs_all_models = []
roc_curve_all_runs_all_models = []
f1_scores_all_runs_all_models = []

for setting in all_settings:
    curr_dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(curr_dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {curr_dataset_output_dir}')
            
        run_folders_list = []
        for item in os.listdir(curr_dataset_output_dir):
            curr_path = os.path.join(curr_dataset_output_dir, item)
            if os.path.isdir(curr_path) and 'run' in item:
                run_folders_list.append(item)

        print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

        run_folders_paths = []
        curr_pred_folders_paths = []
        for run_folder in run_folders_list:
            run_path = os.path.join(curr_dataset_output_dir, run_folder)
            run_folders_paths.append(run_path)
            pred_run_path = os.path.join(run_path, 'pred')
            curr_pred_folders_paths.append(pred_run_path)
            
        for run_name, pred_folder in zip(run_folders_list, curr_pred_folders_paths):
            with open(f'{pred_folder}/performance_scores_{setting["dataset_nr"]}_{setting["embedding_method"]}.pkl', 'rb') as f:
                loaded_info = pickle.load(f)

            auc_roc_score = loaded_info['ROC AUC Score']
            formatted_auc_roc_score = float(auc_roc_score)
            auc_roc_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                        'ROC AUC Score': formatted_auc_roc_score}
            final_test_auc_roc_scores_all_runs_all_models.append(auc_roc_score_per_run)

            roc_fpr_scores = loaded_info['ROC FPR']
            roc_tpr_scores = loaded_info['ROC TPR']
            
            for fpr, tpr in zip(roc_fpr_scores, roc_tpr_scores):
                auc_per_threshold_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}',
                                             'ROC FPR': fpr, 'ROC TPR': tpr}
                roc_curve_all_runs_all_models.append(auc_per_threshold_per_run)

            f1_score = loaded_info['F1 Score']
            formatted_f1_score = float(f1_score)
            f1_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                'F1 Score': formatted_f1_score}
            f1_scores_all_runs_all_models.append(f1_score_per_run)

            print(f'F1-Score in the test set of dataset {setting["dataset_nr"]} and method {setting["embedding_method"]}:', f1_score)
            print(classification_report(loaded_info['True Labels'], loaded_info['Predicted Labels']))

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v
A total of 10 runs will be included in the analysis.
F1-Score in the test set of dataset 1 and method e2v: 0.9360192201071891
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     26952
           1       0.93      0.94      0.94     26952

    accuracy                           0.94     53904
   macro avg       0.94      0.94      0.94     53904
weighted avg       0.94      0.94      0.94     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9390599078341014
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     26952
           1       0.93      0.95      0.94     26952

    accuracy                           0.94     53904
   macro avg       0.94      0.94      0.94     53904
weighted avg       0.94      0.94      0.94     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9282963575225894
              precision    recall  f1-score   support

           0       0.92      0.94      0.93     26952
           1       0.94      0.92      0.93     26952

    accuracy                           0.93     53904
   macro avg       0.93      0.93      0.93     53904
weighted avg       0.93      0.93      0.93     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9361890041951865
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     26952
           1       0.93      0.94      0.94     26952

    accuracy                           0.94     53904
   macro avg       0.94      0.94      0.94     53904
weighted avg       0.94      0.94      0.94     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9392401793457202
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     26952
           1       0.93      0.94      0.94     26952

    accuracy                           0.94     53904
   macro avg       0.94      0.94      0.94     53904
weighted avg       0.94      0.94      0.94     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9405796835082431
              precision    recall  f1-score   support

           0       0.95      0.93      0.94     26952
           1       0.93      0.95      0.94     26952

    accuracy                           0.94     53904
   macro avg       0.94      0.94      0.94     53904
weighted avg       0.94      0.94      0.94     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9326229326229326
              precision    recall  f1-score   support

           0       0.93      0.93      0.93     26952
           1       0.93      0.94      0.93     26952

    accuracy                           0.93     53904
   macro avg       0.93      0.93      0.93     53904
weighted avg       0.93      0.93      0.93     53904

F1-Score in the test set of dataset 1 and method e2v: 0.6561808920362777
              precision    recall  f1-score   support

           0       0.66      1.00      0.80     26952
           1       0.99      0.49      0.66     26952

    accuracy                           0.74     53904
   macro avg       0.83      0.74      0.73     53904
weighted avg       0.83      0.74      0.73     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9158485273492286
              precision    recall  f1-score   support

           0       0.92      0.91      0.91     26952
           1       0.91      0.92      0.92     26952

    accuracy                           0.92     53904
   macro avg       0.92      0.92      0.92     53904
weighted avg       0.92      0.92      0.92     53904

F1-Score in the test set of dataset 1 and method e2v: 0.9402364031373127
              precision    recall  f1-score   support

           0       0.95      0.93      0.94     26952
           1       0.93      0.95      0.94     26952

    accuracy                           0.94     53904
   macro avg       0.94      0.94      0.94     53904
weighted avg       0.94      0.94      0.94     53904

First, run the edge2vec embedding script. Then, run this script.

In [6]:
roc_curve_all_runs_all_models = pd.DataFrame(roc_curve_all_runs_all_models)
roc_curve_all_runs_all_models

        Model   ROC FPR   ROC TPR
0      g1_e2v  0.000000  0.000000
1      g1_e2v  0.000148  0.153458
2      g1_e2v  0.000148  0.154126
3      g1_e2v  0.000148  0.155091
4      g1_e2v  0.000148  0.155684
...       ...       ...       ...
41104  g1_e2v  0.999666  0.999852
41105  g1_e2v  0.999666  0.999926
41106  g1_e2v  0.999852  0.999926
41107  g1_e2v  0.999852  1.000000
41108  g1_e2v  1.000000  1.000000

[41109 rows x 3 columns]

In [7]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'ROC TPR/ROC FPR Distribution over Each Run for Each Model')
sns.scatterplot(data=roc_curve_all_runs_all_models, x="ROC FPR", y="ROC TPR", hue="Model", s=1)
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.legend(markerscale=10)

fig.savefig(f'{curr_output_dir}/roc_curves.png', bbox_inches='tight')
fig.clear()

## F1 Scores

In [8]:
f1_scores_all_runs_all_models = pd.DataFrame(f1_scores_all_runs_all_models)
f1_scores_all_runs_all_models

    Model  F1 Score
0  g1_e2v  0.936019
1  g1_e2v  0.939060
2  g1_e2v  0.928296
3  g1_e2v  0.936189
4  g1_e2v  0.939240
5  g1_e2v  0.940580
6  g1_e2v  0.932623
7  g1_e2v  0.656181
8  g1_e2v  0.915849
9  g1_e2v  0.940236

In [9]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'F1 Scores Overview for Each Model')
sns.barplot(f1_scores_all_runs_all_models, x="Model", y="F1 Score", errorbar="sd", color='cornflowerblue')
ax.bar_label(ax.containers[0], fontsize=10, padding=5)
ax.set_xlabel('Model Variant')
ax.set_ylabel('F1 Score')

fig.savefig(f'{curr_output_dir}/f1_scores.png', bbox_inches='tight')
fig.clear()

## Final AUC-ROC Scores

In [10]:
final_test_auc_roc_scores_all_runs_all_models = pd.DataFrame(final_test_auc_roc_scores_all_runs_all_models)
final_test_auc_roc_scores_all_runs_all_models

    Model  ROC AUC Score
0  g1_e2v       0.974881
1  g1_e2v       0.975704
2  g1_e2v       0.973653
3  g1_e2v       0.975204
4  g1_e2v       0.973902
5  g1_e2v       0.976678
6  g1_e2v       0.974351
7  g1_e2v       0.971160
8  g1_e2v       0.962830
9  g1_e2v       0.974757

In [11]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'AUC-ROC Scores Overview for Each Model')
sns.barplot(final_test_auc_roc_scores_all_runs_all_models, x="Model", y="ROC AUC Score", errorbar="sd")
ax.bar_label(ax.containers[0], fontsize=10, padding=10)
ax.set_ylim(0.85,1) # 0.85, 1
ax.set_xlabel('Model Variant')
ax.set_ylabel('AUC-ROC Score')

fig.savefig(f'{curr_output_dir}/auc_roc_scores.png', bbox_inches='tight')
fig.clear()

# Plot Training Curve

In [12]:
auc_scores_all_runs = pd.DataFrame(auc_scores_all_runs)
auc_scores_all_runs

          run       name  iteration     score
0     run_001  AUC Train          0  0.981828
1     run_001  AUC Train          1  0.977562
2     run_001  AUC Train          2  0.978060
3     run_001  AUC Train          3  0.974611
4     run_001  AUC Train          4  0.972791
...       ...        ...        ...       ...
4465  run_010   AUC Test        144  0.973850
4466  run_010   AUC Test        145  0.973972
4467  run_010   AUC Test        146  0.974171
4468  run_010   AUC Test        147  0.974221
4469  run_010   AUC Test        148  0.974220

[4470 rows x 4 columns]

In [13]:
auc_loss_scores_all_runs = pd.DataFrame(auc_loss_scores_all_runs)
auc_loss_scores_all_runs

          run                name  iteration     score
0     run_001           AUC Train          0  0.981828
1     run_001           AUC Train          1  0.977562
2     run_001           AUC Train          2  0.978060
3     run_001           AUC Train          3  0.974611
4     run_001           AUC Train          4  0.972791
...       ...                 ...        ...       ...
5955  run_010  Cross-Entropy Loss        144 -0.383198
5956  run_010  Cross-Entropy Loss        145 -0.382148
5957  run_010  Cross-Entropy Loss        146 -0.380017
5958  run_010  Cross-Entropy Loss        147 -0.384980
5959  run_010  Cross-Entropy Loss        148 -0.383737

[5960 rows x 4 columns]

In [14]:
fig, ax = plt.subplots(figsize=(8, 8))

ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(0.8,1) # 0.85, 1
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC Score')

print(dataset_output_dir)
fig.savefig(f'{dataset_output_dir}/training_curve.png', bbox_inches='tight')
fig.clear()

c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v

In [15]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_loss_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(top=1)
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC/log10(Loss)')

fig.savefig(f'{dataset_output_dir}/training_curve_with_loss.png', bbox_inches='tight')
fig.clear()

# Similarity between top scoring symptom-drug pairs

In [16]:
drug_symptom_pairs_per_run = []

for index, pred_path in enumerate(pred_folders_paths):
    with open(f'{pred_path}/candidates_per_symptom_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_list = pickle.load(f)
        
        drug_symptom_pairs = []
        
        for _, row in loaded_list.iterrows():
            symptom_id = row['Symptom']
            candidates = row['Candidates']
            
            for candidate in candidates:
                drug_symptom_pairs.append(tuple([symptom_id, candidate]))
                
        total_drug_symptom_pairs = len(drug_symptom_pairs)
    
    drug_symptom_pairs_per_run.append(drug_symptom_pairs)

In [17]:
similarity_matrix = {}
ratios_non_diagonals = []

for index1, pairs1 in enumerate(drug_symptom_pairs_per_run):
    
    similarities = {}
    
    for index2, pairs2 in enumerate(drug_symptom_pairs_per_run):
        overlap = set([tuple(sorted(ele)) for ele in pairs1]) & set([tuple(sorted(ele)) for ele in pairs2])
        ratio_overlap = len(overlap) / total_drug_symptom_pairs * 100
        
        similarities[f'run {index2+1}'] = ratio_overlap
        
        if index1 != index2:
            ratios_non_diagonals.append(ratio_overlap)
        
    similarity_matrix[f'run {index1+1}'] = similarities
    
similarity_matrix_df = pd.DataFrame(similarity_matrix)
similarity_matrix_df

,run 1,run 2,run 3,run 4,run 5,run 6,run 7,run 8,run 9,run 10
run 1,100.000000,29.885057,21.839080,15.517241,24.712644,32.758621,28.160920,29.310345,16.091954,35.632184
run 2,29.885057,100.000000,38.505747,21.264368,27.586207,41.379310,36.781609,47.701149,27.586207,46.551724
run 3,21.839080,38.505747,100.000000,24.712644,25.287356,29.310345,34.482759,47.126437,28.735632,35.057471
run 4,15.517241,21.264368,24.712644,100.000000,47.701149,29.885057,21.839080,24.712644,24.712644,40.804598
run 5,24.712644,27.586207,25.287356,47.701149,100.000000,41.954023,31.609195,27.586207,17.816092,41.379310
run 6,32.758621,41.379310,29.310345,29.885057,41.954023,100.000000,57.471264,54.597701,17.816092,55.172414
run 7,28.160920,36.781609,34.482759,21.839080,31.609195,57.471264,100.000000,62.068966,24.712644,46.551724
run 8,29.310345,47.701149,47.126437,24.712644,27.586207,54.597701,62.068966,100.000000,25.862069,49.425287
run 9,16.091954,27.586207,28.735632,24.712644,17.816092,17.816092,24.712644,25.862069,100.000000,40.229885
run 10,35.632184,46.551724,35.057471,40.804598,41.379310,55.172414,46.551724,49.425287,40.229885,100.000000

In [18]:
mean_overlap_ratio = np.mean(ratios_non_diagonals)
median_overlap_ratio = np.median(ratios_non_diagonals)
print('Mean:', mean_overlap_ratio)
print('Median:', median_overlap_ratio)

Mean: 33.99744572158365
Median: 29.88505747126437

In [19]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Overlap ratio (Mean: {round(mean_overlap_ratio, 2)}, Median: {round(median_overlap_ratio, 2)}) between list of predicted symptom-drug pairs per run on dataset {dataset_nr} {concept_changes_str}')
sns.heatmap(similarity_matrix_df, annot=True, fmt='.1f', linewidths=0.5, ax=ax, cmap='RdYlGn')
ax.collections[0].set_clim(0,100)

fig.savefig(f'{dataset_output_dir}/overlap_between_runs.png', bbox_inches='tight')
fig.clear()

In [20]:
for i in range(0, len(drug_symptom_pairs_per_run)):
    if i == 0:
        overlapping_pairs_all_runs = set(drug_symptom_pairs_per_run[i])
    else:
        overlapping_pairs_all_runs = overlapping_pairs_all_runs & set(drug_symptom_pairs_per_run[i])
            
print(f'There are {len(overlapping_pairs_all_runs)} symptom-drug pairs that are found in the top list of drug candidates in {len(drug_symptom_pairs_per_run)} runs: \n {overlapping_pairs_all_runs}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{dataset_nr}_{embedding_method}{fixed_emb}.pkl', 'wb') as f:
    pickle.dump(overlapping_pairs_all_runs, f)

There are 7 symptom-drug pairs that are found in the top list of drug candidates in 10 runs:
 {('HP:0002059', '1990'), ('HP:0002067', '578'), ('HP:0001288', '578'), ('HP:0001250', '1990'), ('HP:0002059', '2054'), ('HP:0002171', '578'), ('HP:0002591', '578')}

In [22]:
same_drug_symptom_pairs_thresholded = set()

threshold = 0.7
total_runs = len(drug_symptom_pairs_per_run)
min_nr_runs = int(threshold * total_runs)

for i in range(0, len(drug_symptom_pairs_per_run)):
    for pair in drug_symptom_pairs_per_run[i]:
        same_pairs = 0
        for j in range(0, len(drug_symptom_pairs_per_run)):
            for pair_to_compare in drug_symptom_pairs_per_run[j]:
                if pair == pair_to_compare:
                    same_pairs += 1
                        
        #print(f'For pair {pair} from run {i}, there are {same_pairs} same pairs found in list of all runs.')
        if same_pairs >= min_nr_runs:
            same_drug_symptom_pairs_thresholded.add(pair)
            
print(f'There are {len(same_drug_symptom_pairs_thresholded)} symptom-drug pairs that are found in the top list of drug candidates in at least {min_nr_runs} of the {total_runs} runs: \n {same_drug_symptom_pairs_thresholded}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_{min_nr_runs}_runs_{dataset_nr}_{embedding_method}{fixed_emb}{suffix}.pkl', 'wb') as f:
    pickle.dump(same_drug_symptom_pairs_thresholded, f)

There are 41 symptom-drug pairs that are found in the top list of drug candidates in at least 7 of the 10 runs:
 {('HP:0001347', '1990'), ('HP:0002059', '1990'), ('HP:0001288', '578'), ('HP:0000716', '2054'), ('HP:0002529', '5359'), ('HP:0000751', '5359'), ('HP:0002355', '2054'), ('HP:0000722', '2054'), ('HP:0002072', '2054'), ('HP:0002171', '578'), ('HP:0000739', '1990'), ('HP:0000718', '1990'), ('HP:0000716', '1996'), ('HP:0000713', '1990'), ('HP:0002591', '578'), ('HP:0002500', '1990'), ('HP:0002063', '1990'), ('HP:0001250', '1996'), ('HP:0001272', '1990'), ('HP:0000722', '2123'), ('HP:0002066', '1990'), ('HP:0002540', '2054'), ('HP:0000716', '1990'), ('HP:0001332', '2054'), ('HP:0002355', '1990'), ('HP:0000722', '1990'), ('HP:0002072', '1990'), ('HP:0002067', '578'), ('HP:0001347', '2054'), ('HP:0001250', '1990'), ('HP:0002059', '2054'), ('HP:0000746', '5359'), ('HP:0002169', '2123'), ('HP:0002540', '1990'), ('HP:0000718', '2054'), ('HP:0001332', '1990'), ('HP:0002500', '2054'), ('HP:0000739', '1996'), ('HP:0002063', '2054'), ('HP:0001272', '2054'), ('HP:0002066', '2054')}

# Symptoms related to DMD

In [23]:
edges = pd.read_csv(f'output/{disease_prefix}/indexed_edges_{dataset_nr}{suffix}.csv')
edges

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSSSCG00000040510,KIF9,5,1827,0
1,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ENSEMBL:ENSCAFG00000013358,ENSEMBL:ENSCAFG00000013358,5,12004,0
2,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,Xenbase:XB-GENE-995481,kif9,5,11336,0
3,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,HGNC:16666,KIF9,3,13100,0
4,ENSEMBL:ENSPTRG00000014867,ENSEMBL:ENSPTRG00000014867,5,997,in 1 to 1 orthology relationship with,ZFIN:ZDB-GENE-160728-129,kif9,5,5001,0
...,...,...,...,...,...,...,...,...,...,...
228994,2491,sufentanil,2,1243,targets,HGNC:8156,OPRM1,3,9620,15
228995,Coriell:GM04198,NIGMS-GM04198,4,4421,has role in modeling,MONDO:0007739,Huntington disease,1,6883,8
228996,1690,pethidine,2,823,targets,HGNC:8156,OPRM1,3,9620,15
228997,Coriell:GM04818,NIGMS-GM04818,4,9339,has role in modeling,MONDO:0007739,Huntington disease,1,6883,8
228998,3535,rutoside,2,1699,targets,HGNC:29079,KDM1A,3,10737,15

In [24]:
if dataset_nr == 1:
    pheno_rel = 'has phenotype'
else:
    pheno_rel = 'associated with phenotype'
    
_, relation_labels = pd.factorize(edges['relation'])

if disease_prefix == 'dmd':
    disease_ID = 'MONDO:0010679'
elif disease_prefix == 'hd':
    disease_ID = 'MONDO:0007739'
    
relation_index = list(relation_labels).index(pheno_rel)

symptoms = edges[(edges['head'] == disease_ID) & (edges['type'] == relation_index)]

print(f'A total of {symptoms.shape[0]} symptoms found that are associated with {disease_ID}')
symptoms

A total of 58 symptoms found that are associated with MONDO:0007739

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
150937,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000716,Depression,1,13668,3
150938,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0040140,Degeneration of the striatum,1,5086,3
150939,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001332,Dystonia,1,12933,3
150940,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000739,Anxiety,1,1789,3
150941,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0031845,Abnormal libido,1,14311,3
150942,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000718,Aggressive behavior,1,3673,3
150943,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000722,Obsessive-compulsive behavior,1,12938,3
150944,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0025401,Staring gaze,1,11096,3
150945,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001272,Cerebellar atrophy,1,6473,3
150946,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000734,Disinhibition,1,7722,3
150947,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0031589,Suicidal ideation,1,4670,3
150948,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002066,Gait ataxia,1,2028,3
150949,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001268,Mental deterioration,1,10550,3
150950,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0031473,Hostility,1,6571,3
150951,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000496,Abnormality of eye movement,1,8786,3
150952,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0030842,Choking episodes,1,9177,3
150953,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002067,Bradykinesia,1,7072,3
150954,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002141,Gait imbalance,1,1065,3
150955,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001336,Myoclonus,1,13378,3
150956,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000713,Agitation,1,5935,3
150957,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002171,Gliosis,1,3363,3
150958,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002072,Chorea,1,14731,3
150959,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002312,Clumsiness,1,2824,3
150960,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001824,Weight loss,1,13123,3
150961,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0100785,Insomnia,1,6088,3
150962,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0200136,Oral-pharyngeal dysphagia,1,13978,3
150963,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000726,Dementia,1,10333,3
150964,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001250,Seizure,1,8961,3
150965,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002591,Polyphagia,1,4827,3
150966,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000737,Irritability,1,11896,3
150967,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0009088,Speech articulation difficulties,1,1317,3
150968,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000746,Delusions,1,4154,3
150969,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001262,Excessive daytime somnolence,1,12562,3
150970,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000738,Hallucinations,1,5925,3
150971,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000741,Apathy,1,8154,3
150972,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002169,Clonus,1,9999,3
150973,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0010794,Impaired visuospatial constructive cognition,1,9644,3
150974,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002540,Inability to walk,1,14773,3
150975,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0045082,Decreased body mass index,1,3165,3
150976,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002529,Neuronal loss in central nervous system,1,917,3
150977,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002355,Difficulty walking,1,2520,3
150978,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0007010,Poor fine motor coordination,1,9801,3
150979,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0030955,Alcoholism,1,14527,3
150980,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002059,Cerebral atrophy,1,8158,3
150981,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0004305,Involuntary movements,1,4177,3
150982,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001347,Hyperreflexia,1,12039,3
150983,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0004408,Abnormality of the sense of smell,1,12080,3
150984,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002300,Mutism,1,12647,3
150986,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0000751,Personality changes,1,1369,3
150987,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002063,Rigidity,1,13477,3
150988,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002500,Abnormal cerebral white matter morphology,1,434,3
150989,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0003487,Babinski sign,1,13239,3
150990,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0031843,Bradyphrenia,1,13783,3
150991,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002340,Caudate atrophy,1,830,3
150992,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0001288,Gait disturbance,1,13592,3
150993,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0003324,Generalized muscle weakness,1,4071,3
150994,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0003107,Abnormal circulating cholesterol concentration,1,5436,3
150995,MONDO:0007739,Huntington disease,1,6883,has phenotype,HP:0002354,Memory impairment,1,1951,3

In [25]:
symptoms_df = symptoms[['tail', 'label_tail']]
symptoms_df = symptoms_df.rename(columns={'tail': 'Symptom ID', 'label_tail': 'Symptom'})
symptoms_df.to_csv(f'{curr_output_dir}/{disease_prefix}relatedsymptoms.csv', index=False)

# Check overlap between each model

In [26]:
nodes = pd.read_csv(f'output/{disease_prefix}/indexed_nodes_{dataset_nr}.csv')
nodes.drop('index_id', axis=1, inplace=True)
nodes['semantic'] = nodes['semantic'].astype('category')
nodes

,id,semantic,label,semantic_id
0,ENSEMBL:ENSCAFG00000047980,ORTH,ENSEMBL:ENSCAFG00000047980,5
1,ENSEMBL:ENSFCAG00000005686,ORTH,ENSEMBL:ENSFCAG00000005686,5
2,NCBIGene:110438919,GENE,LOC110438919,3
3,ENSEMBL:ENSBTAG00000000219,ORTH,ENSEMBL:ENSBTAG00000000219,5
4,ZFIN:ZDB-GENE-040426-1961,ORTH,dynll1,5
...,...,...,...,...
14828,HP:0000054,DISO,Micropenis,1
14829,HGNC:7734,GENE,NEFM,3
14830,ENSEMBL:ENSBTAG00000003758,ORTH,TKT,5
14831,WBPhenotype:0001889,DISO,body wall muscle sarcomere morphology variant,1
14832,WBPhenotype:0001172,DISO,programmed cell death variant,1

In [27]:
if dataset_nr == 1:
    drug_semantic = 'DRUG'
else:
    drug_semantic = 'drug'

nodes[nodes['semantic'] == drug_semantic]

         id semantic                   label  semantic_id
52       90     DRUG               adenosine            2
53       91     DRUG  adenosine triphosphate            2
59      114     DRUG              alfentanil            2
69      143     DRUG               alvimopan            2
81      176     DRUG              amiodarone            2
...     ...      ...                     ...          ...
2599   5389     DRUG               tucatinib            2
2606   5406     DRUG             oliceridine            2
2620   5442     DRUG             trilaciclib            2
2624   5460     DRUG             samidorphan            2
11188  4903     DRUG              nintedanib            2

[215 rows x 4 columns]

In [28]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)

overlapping_pairs = []

for setting in all_settings:
    dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {setting["dataset_nr"]} exists and will be loaded: {dataset_output_dir}')
        
        with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}.pkl', 'rb') as f:
            loaded_list = pickle.load(f)
            overlapping_pairs.append(loaded_list)
            
            pair_dict_list = []
            for pair in loaded_list:
                symptom_id, drug_id = pair
                
                symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
                
                drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
                pair_dict_list.append({'Drug': drug_name, 'Symptom ID': symptom_id, 'Symptom': symptom_name})
                
            overlapping_all_runs_df = pd.DataFrame(pair_dict_list)
            overlapping_all_runs_df.to_csv(f'{dataset_output_dir}/symptom_drug_pairs_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}.csv', index=False)

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\hd\g1_e2v
First, run the edge2vec embedding script. Then, run this script.

In [29]:
dataset1_emb_overlap = overlapping_pairs[0].intersection(overlapping_pairs[1])
for pair in dataset1_emb_overlap:
    symptom_id, drug_id = pair
    symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
    drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
    print(drug_name, 'treats', symptom_name)

IndexError: list index out of range