# Import Libraries

In [34]:
import os
import pickle
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics import classification_report

# Set Parameters

In [35]:
dataset_nr = 2
assert dataset_nr == 1 or 2

disease_prefix = 'dmd'
assert disease_prefix == 'dmd' or 'hd'

embedding_method = 'e2v'
assert embedding_method == 'e2v' or 'm2v'

# Additional experiments
NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = None  # set to None when no conceptual changes are wanted

if concept_changes:
    concept_changes_str = concept_changes
else:
    concept_changes_str = ''
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''

seeded_emb = False

if seeded_emb:
    fixed_emb = '_seeded'
else:
    fixed_emb = ''
    
if seeded_emb:
    title_seeded = ' with fixed node embeddings'
else:
    title_seeded = ''

# Get Result Paths

In [36]:
curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)
dataset_output_dir = os.path.join(curr_output_dir, f'g{dataset_nr}_{embedding_method}{fixed_emb}{suffix}')

if not os.path.exists(dataset_output_dir):
    print('First, run the edge2vec embedding script. Then, run this script.')
else:
    print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {dataset_output_dir}')
    
run_folders_list = []
for item in os.listdir(dataset_output_dir):
    curr_path = os.path.join(dataset_output_dir, item)
    if os.path.isdir(curr_path) and 'run' in item:
        run_folders_list.append(item)

print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

run_folders_paths = []
pred_folders_paths = []
for run_folder in run_folders_list:
    run_path = os.path.join(dataset_output_dir, run_folder)
    run_folders_paths.append(run_path)
    pred_run_path = os.path.join(run_path, 'pred')
    pred_folders_paths.append(pred_run_path)
    print(pred_run_path)

Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v
A total of 10 runs will be included in the analysis.
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_001\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_002\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_003\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_004\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_005\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_006\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_007\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_008\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_009\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v\run_010\pred

In [37]:
auc_scores_all_runs = []
auc_loss_scores_all_runs = []

for run_name, pred_folder in zip(run_folders_list, pred_folders_paths):
    with open(f'{pred_folder}/performance_scores_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_info = pickle.load(f)
        
    keys = ['AUC Train', 'AUC Validation', 'AUC Test']
    for key in keys:
        auc_scores = loaded_info[key]
        for index, auc_score in enumerate(auc_scores):
            auc_scores_per_run = {'run': run_name, 'name': key, 'iteration': index, 'score': auc_score}
            auc_scores_all_runs.append(auc_scores_per_run)
            auc_loss_scores_all_runs.append(auc_scores_per_run)

    loss_scores = loaded_info['Loss']
    for index, loss_score in enumerate(loss_scores):
        formatted_loss_score = float(np.log10(loss_score))
        loss_scores_per_run = {'run': run_name, 'name': 'Cross-Entropy Loss', 'iteration': index, 'score': formatted_loss_score}
        auc_loss_scores_all_runs.append(loss_scores_per_run)

# Plot ROC Curves, AUC-ROC Scores and F1 Scores for Each Model

## ROC Curves

In [38]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)

final_test_auc_roc_scores_all_runs_all_models = []
roc_curve_all_runs_all_models = []
f1_scores_all_runs_all_models = []

for setting in all_settings:
    curr_dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(curr_dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {curr_dataset_output_dir}')
            
        run_folders_list = []
        for item in os.listdir(curr_dataset_output_dir):
            curr_path = os.path.join(curr_dataset_output_dir, item)
            if os.path.isdir(curr_path) and 'run' in item:
                run_folders_list.append(item)

        print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

        run_folders_paths = []
        curr_pred_folders_paths = []
        for run_folder in run_folders_list:
            run_path = os.path.join(curr_dataset_output_dir, run_folder)
            run_folders_paths.append(run_path)
            pred_run_path = os.path.join(run_path, 'pred')
            curr_pred_folders_paths.append(pred_run_path)
            
        for run_name, pred_folder in zip(run_folders_list, curr_pred_folders_paths):
            with open(f'{pred_folder}/performance_scores_{setting["dataset_nr"]}_{setting["embedding_method"]}.pkl', 'rb') as f:
                loaded_info = pickle.load(f)

            auc_roc_score = loaded_info['ROC AUC Score']
            formatted_auc_roc_score = float(auc_roc_score)
            auc_roc_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                        'ROC AUC Score': formatted_auc_roc_score}
            final_test_auc_roc_scores_all_runs_all_models.append(auc_roc_score_per_run)

            roc_fpr_scores = loaded_info['ROC FPR']
            roc_tpr_scores = loaded_info['ROC TPR']
            
            for fpr, tpr in zip(roc_fpr_scores, roc_tpr_scores):
                auc_per_threshold_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}',
                                             'ROC FPR': fpr, 'ROC TPR': tpr}
                roc_curve_all_runs_all_models.append(auc_per_threshold_per_run)

            f1_score = loaded_info['F1 Score']
            formatted_f1_score = float(f1_score)
            f1_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                'F1 Score': formatted_f1_score}
            f1_scores_all_runs_all_models.append(f1_score_per_run)

            print(f'F1-Score in the test set of dataset {setting["dataset_nr"]} and method {setting["embedding_method"]}:', f1_score)
            print(classification_report(loaded_info['True Labels'], loaded_info['Predicted Labels']))

Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g1_e2v
A total of 10 runs will be included in the analysis.
F1-Score in the test set of dataset 1 and method e2v: 0.9392509707319109
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     11958
           1       0.94      0.94      0.94     11958

    accuracy                           0.94     23916
   macro avg       0.94      0.94      0.94     23916
weighted avg       0.94      0.94      0.94     23916

F1-Score in the test set of dataset 1 and method e2v: 0.9355134729290064
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     11958
           1       0.93      0.94      0.94     11958

    accuracy                           0.94     23916
   macro avg       0.94      0.94      0.94     23916
weighted avg       0.94      0.94      0.94     23916

F1-Score in the test set of dataset 1 and method e2v: 0.9295480202366517
              precision    recall  f1-score   support

           0       0.93      0.93      0.93     11958
           1       0.93      0.93      0.93     11958

    accuracy                           0.93     23916
   macro avg       0.93      0.93      0.93     23916
weighted avg       0.93      0.93      0.93     23916

F1-Score in the test set of dataset 1 and method e2v: 0.9329991645781119
              precision    recall  f1-score   support

           0       0.93      0.93      0.93     11958
           1       0.93      0.93      0.93     11958

    accuracy                           0.93     23916
   macro avg       0.93      0.93      0.93     23916
weighted avg       0.93      0.93      0.93     23916

F1-Score in the test set of dataset 1 and method e2v: 0.9354529144239996
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     11958
           1       0.93      0.94      0.94     11958

    accuracy                           0.94     23916
   macro avg       0.94      0.94      0.94     23916
weighted avg       0.94      0.94      0.94     23916

F1-Score in the test set of dataset 1 and method e2v: 0.936333653404584
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     11958
           1       0.93      0.94      0.94     11958

    accuracy                           0.94     23916
   macro avg       0.94      0.94      0.94     23916
weighted avg       0.94      0.94      0.94     23916

F1-Score in the test set of dataset 1 and method e2v: 0.9285179329283515
              precision    recall  f1-score   support

           0       0.93      0.92      0.93     11958
           1       0.92      0.93      0.93     11958

    accuracy                           0.93     23916
   macro avg       0.93      0.93      0.93     23916
weighted avg       0.93      0.93      0.93     23916

F1-Score in the test set of dataset 1 and method e2v: 0.925567686495911
              precision    recall  f1-score   support

           0       0.93      0.92      0.92     11958
           1       0.92      0.93      0.93     11958

    accuracy                           0.93     23916
   macro avg       0.93      0.93      0.93     23916
weighted avg       0.93      0.93      0.93     23916

F1-Score in the test set of dataset 1 and method e2v: 0.9305115814030994
              precision    recall  f1-score   support

           0       0.93      0.93      0.93     11958
           1       0.93      0.93      0.93     11958

    accuracy                           0.93     23916
   macro avg       0.93      0.93      0.93     23916
weighted avg       0.93      0.93      0.93     23916

F1-Score in the test set of dataset 1 and method e2v: 0.9253668586805702
              precision    recall  f1-score   support

           0       0.92      0.93      0.93     11958
           1       0.93      0.92      0.93     11958

    accuracy                           0.93     23916
   macro avg       0.93      0.93      0.93     23916
weighted avg       0.93      0.93      0.93     23916

Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v
A total of 10 runs will be included in the analysis.
F1-Score in the test set of dataset 2 and method e2v: 0.8915906788247214
              precision    recall  f1-score   support

           0       0.97      0.78      0.87     12136
           1       0.82      0.98      0.89     12136

    accuracy                           0.88     24272
   macro avg       0.90      0.88      0.88     24272
weighted avg       0.90      0.88      0.88     24272

F1-Score in the test set of dataset 2 and method e2v: 0.8889055472263868
              precision    recall  f1-score   support

           0       0.97      0.78      0.86     12136
           1       0.82      0.98      0.89     12136

    accuracy                           0.88     24272
   macro avg       0.89      0.88      0.88     24272
weighted avg       0.89      0.88      0.88     24272

F1-Score in the test set of dataset 2 and method e2v: 0.9031119297033882
              precision    recall  f1-score   support

           0       0.96      0.82      0.89     12136
           1       0.85      0.97      0.90     12136

    accuracy                           0.90     24272
   macro avg       0.90      0.90      0.90     24272
weighted avg       0.90      0.90      0.90     24272

F1-Score in the test set of dataset 2 and method e2v: 0.9013591198081242
              precision    recall  f1-score   support

           0       0.97      0.81      0.88     12136
           1       0.84      0.98      0.90     12136

    accuracy                           0.89     24272
   macro avg       0.90      0.89      0.89     24272
weighted avg       0.90      0.89      0.89     24272

F1-Score in the test set of dataset 2 and method e2v: 0.8928786964393483
              precision    recall  f1-score   support

           0       0.97      0.79      0.87     12136
           1       0.82      0.98      0.89     12136

    accuracy                           0.88     24272
   macro avg       0.90      0.88      0.88     24272
weighted avg       0.90      0.88      0.88     24272

F1-Score in the test set of dataset 2 and method e2v: 0.8989512739938668
              precision    recall  f1-score   support

           0       0.97      0.80      0.88     12136
           1       0.83      0.98      0.90     12136

    accuracy                           0.89     24272
   macro avg       0.90      0.89      0.89     24272
weighted avg       0.90      0.89      0.89     24272

F1-Score in the test set of dataset 2 and method e2v: 0.9015536187949981
              precision    recall  f1-score   support

           0       0.98      0.81      0.88     12136
           1       0.83      0.98      0.90     12136

    accuracy                           0.89     24272
   macro avg       0.91      0.89      0.89     24272
weighted avg       0.91      0.89      0.89     24272

F1-Score in the test set of dataset 2 and method e2v: 0.8959818902093944
              precision    recall  f1-score   support

           0       0.97      0.79      0.87     12136
           1       0.83      0.98      0.90     12136

    accuracy                           0.89     24272
   macro avg       0.90      0.89      0.89     24272
weighted avg       0.90      0.89      0.89     24272

F1-Score in the test set of dataset 2 and method e2v: 0.8979156346454292
              precision    recall  f1-score   support

           0       0.97      0.81      0.88     12136
           1       0.84      0.97      0.90     12136

    accuracy                           0.89     24272
   macro avg       0.90      0.89      0.89     24272
weighted avg       0.90      0.89      0.89     24272

F1-Score in the test set of dataset 2 and method e2v: 0.8906074029581801
              precision    recall  f1-score   support

           0       0.97      0.78      0.87     12136
           1       0.82      0.98      0.89     12136

    accuracy                           0.88     24272
   macro avg       0.89      0.88      0.88     24272
weighted avg       0.89      0.88      0.88     24272

In [39]:
roc_curve_all_runs_all_models = pd.DataFrame(roc_curve_all_runs_all_models)
roc_curve_all_runs_all_models

        Model   ROC FPR   ROC TPR
0      g1_e2v  0.000000  0.000000
1      g1_e2v  0.000000  0.000167
2      g1_e2v  0.000000  0.020070
3      g1_e2v  0.000000  0.020405
4      g1_e2v  0.000000  0.026259
...       ...       ...       ...
41613  g2_e2v  0.941496  0.999670
41614  g2_e2v  0.941496  0.999835
41615  g2_e2v  0.950725  0.999835
41616  g2_e2v  0.950725  1.000000
41617  g2_e2v  1.000000  1.000000

[41618 rows x 3 columns]

In [40]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'ROC TPR/ROC FPR Distribution over Each Run for Each Model')
sns.scatterplot(data=roc_curve_all_runs_all_models, x="ROC FPR", y="ROC TPR", hue="Model", s=1)
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.legend(markerscale=10)

fig.savefig(f'{curr_output_dir}/roc_curves.png', bbox_inches='tight')
fig.clear()

## F1 Scores

In [41]:
f1_scores_all_runs_all_models = pd.DataFrame(f1_scores_all_runs_all_models)
f1_scores_all_runs_all_models

     Model  F1 Score
0   g1_e2v  0.939251
1   g1_e2v  0.935513
2   g1_e2v  0.929548
3   g1_e2v  0.932999
4   g1_e2v  0.935453
5   g1_e2v  0.936334
6   g1_e2v  0.928518
7   g1_e2v  0.925568
8   g1_e2v  0.930512
9   g1_e2v  0.925367
10  g2_e2v  0.891591
11  g2_e2v  0.888906
12  g2_e2v  0.903112
13  g2_e2v  0.901359
14  g2_e2v  0.892879
15  g2_e2v  0.898951
16  g2_e2v  0.901554
17  g2_e2v  0.895982
18  g2_e2v  0.897916
19  g2_e2v  0.890607

In [42]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'F1 Scores Overview for Each Model')
sns.barplot(f1_scores_all_runs_all_models, x="Model", y="F1 Score", errorbar="sd", color='cornflowerblue')
ax.bar_label(ax.containers[0], fontsize=10, padding=5)
ax.set_xlabel('Model Variant')
ax.set_ylabel('F1 Score')

fig.savefig(f'{curr_output_dir}/f1_scores.png', bbox_inches='tight')
fig.clear()

## Final AUC-ROC Scores

In [43]:
final_test_auc_roc_scores_all_runs_all_models = pd.DataFrame(final_test_auc_roc_scores_all_runs_all_models)
final_test_auc_roc_scores_all_runs_all_models

     Model  ROC AUC Score
0   g1_e2v       0.980523
1   g1_e2v       0.977310
2   g1_e2v       0.974825
3   g1_e2v       0.975103
4   g1_e2v       0.976894
5   g1_e2v       0.977117
6   g1_e2v       0.975046
7   g1_e2v       0.976633
8   g1_e2v       0.975794
9   g1_e2v       0.970014
10  g2_e2v       0.973362
11  g2_e2v       0.971796
12  g2_e2v       0.972394
13  g2_e2v       0.974003
14  g2_e2v       0.971255
15  g2_e2v       0.974543
16  g2_e2v       0.975288
17  g2_e2v       0.976039
18  g2_e2v       0.972541
19  g2_e2v       0.969365

In [44]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'AUC-ROC Scores Overview for Each Model')
sns.barplot(final_test_auc_roc_scores_all_runs_all_models, x="Model", y="ROC AUC Score", errorbar="sd")
ax.bar_label(ax.containers[0], fontsize=10, padding=10)
ax.set_ylim(0.85,1) # 0.85, 1
ax.set_xlabel('Model Variant')
ax.set_ylabel('AUC-ROC Score')

fig.savefig(f'{curr_output_dir}/auc_roc_scores.png', bbox_inches='tight')
fig.clear()

# Plot Training Curve

In [45]:
auc_scores_all_runs = pd.DataFrame(auc_scores_all_runs)
auc_scores_all_runs

          run       name  iteration     score
0     run_001  AUC Train          0  0.974321
1     run_001  AUC Train          1  0.970932
2     run_001  AUC Train          2  0.969036
3     run_001  AUC Train          3  0.966220
4     run_001  AUC Train          4  0.963290
...       ...        ...        ...       ...
2965  run_010   AUC Test         94  0.968283
2966  run_010   AUC Test         95  0.968515
2967  run_010   AUC Test         96  0.968796
2968  run_010   AUC Test         97  0.969083
2969  run_010   AUC Test         98  0.969365

[2970 rows x 4 columns]

In [46]:
auc_loss_scores_all_runs = pd.DataFrame(auc_loss_scores_all_runs)
auc_loss_scores_all_runs

          run                name  iteration     score
0     run_001           AUC Train          0  0.974321
1     run_001           AUC Train          1  0.970932
2     run_001           AUC Train          2  0.969036
3     run_001           AUC Train          3  0.966220
4     run_001           AUC Train          4  0.963290
...       ...                 ...        ...       ...
3955  run_010  Cross-Entropy Loss         94 -0.221490
3956  run_010  Cross-Entropy Loss         95 -0.220521
3957  run_010  Cross-Entropy Loss         96 -0.220199
3958  run_010  Cross-Entropy Loss         97 -0.224559
3959  run_010  Cross-Entropy Loss         98 -0.232656

[3960 rows x 4 columns]

In [47]:
fig, ax = plt.subplots(figsize=(8, 8))

ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(0.8,1) # 0.85, 1
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC Score')

print(dataset_output_dir)
fig.savefig(f'{dataset_output_dir}/training_curve.png', bbox_inches='tight')
fig.clear()

c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v

In [48]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_loss_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(top=1)
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC/log10(Loss)')

fig.savefig(f'{dataset_output_dir}/training_curve_with_loss.png', bbox_inches='tight')
fig.clear()

# Similarity between top scoring symptom-drug pairs

In [49]:
drug_symptom_pairs_per_run = []

for index, pred_path in enumerate(pred_folders_paths):
    with open(f'{pred_path}/candidates_per_symptom_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_list = pickle.load(f)
        
        drug_symptom_pairs = []
        
        for _, row in loaded_list.iterrows():
            symptom_id = row['Symptom']
            candidates = row['Candidates']
            
            for candidate in candidates:
                drug_symptom_pairs.append(tuple([symptom_id, candidate]))
                
        total_drug_symptom_pairs = len(drug_symptom_pairs)
    
    drug_symptom_pairs_per_run.append(drug_symptom_pairs)

In [50]:
similarity_matrix = {}
ratios_non_diagonals = []

for index1, pairs1 in enumerate(drug_symptom_pairs_per_run):
    
    similarities = {}
    
    for index2, pairs2 in enumerate(drug_symptom_pairs_per_run):
        overlap = set([tuple(sorted(ele)) for ele in pairs1]) & set([tuple(sorted(ele)) for ele in pairs2])
        ratio_overlap = len(overlap) / total_drug_symptom_pairs * 100
        
        similarities[f'run {index2+1}'] = ratio_overlap
        
        if index1 != index2:
            ratios_non_diagonals.append(ratio_overlap)
        
    similarity_matrix[f'run {index1+1}'] = similarities
    
similarity_matrix_df = pd.DataFrame(similarity_matrix)
similarity_matrix_df

,run 1,run 2,run 3,run 4,run 5,run 6,run 7,run 8,run 9,run 10
run 1,100.000000,32.142857,35.714286,55.952381,48.809524,39.285714,35.714286,48.809524,41.666667,46.428571
run 2,32.142857,100.000000,33.333333,39.285714,41.666667,35.714286,39.285714,45.238095,27.380952,41.666667
run 3,35.714286,33.333333,100.000000,33.333333,36.904762,38.095238,35.714286,57.142857,32.142857,39.285714
run 4,55.952381,39.285714,33.333333,100.000000,51.190476,40.476190,46.428571,51.190476,45.238095,55.952381
run 5,48.809524,41.666667,36.904762,51.190476,100.000000,38.095238,46.428571,50.000000,46.428571,54.761905
run 6,39.285714,35.714286,38.095238,40.476190,38.095238,100.000000,27.380952,44.047619,38.095238,45.238095
run 7,35.714286,39.285714,35.714286,46.428571,46.428571,27.380952,100.000000,42.857143,35.714286,47.619048
run 8,48.809524,45.238095,57.142857,51.190476,50.000000,44.047619,42.857143,100.000000,35.714286,51.190476
run 9,41.666667,27.380952,32.142857,45.238095,46.428571,38.095238,35.714286,35.714286,100.000000,51.190476
run 10,46.428571,41.666667,39.285714,55.952381,54.761905,45.238095,47.619048,51.190476,51.190476,100.000000

In [51]:
mean_overlap_ratio = np.mean(ratios_non_diagonals)
median_overlap_ratio = np.median(ratios_non_diagonals)
print('Mean:', mean_overlap_ratio)
print('Median:', median_overlap_ratio)

Mean: 42.354497354497354
Median: 41.66666666666667

In [52]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Overlap ratio (Mean: {round(mean_overlap_ratio, 2)}, Median: {round(median_overlap_ratio, 2)}) between list of predicted symptom-drug pairs per run on dataset {dataset_nr} {concept_changes_str}')
sns.heatmap(similarity_matrix_df, annot=True, fmt='.1f', linewidths=0.5, ax=ax, cmap='RdYlGn')
ax.collections[0].set_clim(0,100)

fig.savefig(f'{dataset_output_dir}/overlap_between_runs.png', bbox_inches='tight')
fig.clear()

In [53]:
for i in range(0, len(drug_symptom_pairs_per_run)):
    if i == 0:
        overlapping_pairs_all_runs = set(drug_symptom_pairs_per_run[i])
    else:
        overlapping_pairs_all_runs = overlapping_pairs_all_runs & set(drug_symptom_pairs_per_run[i])
            
print(f'There are {len(overlapping_pairs_all_runs)} symptom-drug pairs that are found in the top list of drug candidates in {len(drug_symptom_pairs_per_run)} runs: \n {overlapping_pairs_all_runs}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{dataset_nr}_{embedding_method}{fixed_emb}.pkl', 'wb') as f:
    pickle.dump(overlapping_pairs_all_runs, f)

There are 4 symptom-drug pairs that are found in the top list of drug candidates in 10 runs:
 {('HP:0003115', '231'), ('HP:0001638', '231'), ('HP:0003701', '1576'), ('HP:0001270', '1795')}

In [55]:
same_drug_symptom_pairs_thresholded = set()

threshold = 0.5
total_runs = len(drug_symptom_pairs_per_run)
min_nr_runs = int(threshold * total_runs)

for i in range(0, len(drug_symptom_pairs_per_run)):
    for pair in drug_symptom_pairs_per_run[i]:
        same_pairs = 0
        for j in range(0, len(drug_symptom_pairs_per_run)):
            for pair_to_compare in drug_symptom_pairs_per_run[j]:
                if pair == pair_to_compare:
                    same_pairs += 1
                        
        #print(f'For pair {pair} from run {i}, there are {same_pairs} same pairs found in list of all runs.')
        if same_pairs >= min_nr_runs:
            same_drug_symptom_pairs_thresholded.add(pair)
            
print(f'There are {len(same_drug_symptom_pairs_thresholded)} symptom-drug pairs that are found in the top list of drug candidates in at least {min_nr_runs} of the {total_runs} runs: \n {same_drug_symptom_pairs_thresholded}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_{min_nr_runs}_runs_{dataset_nr}_{embedding_method}{fixed_emb}{suffix}.pkl', 'wb') as f:
    pickle.dump(same_drug_symptom_pairs_thresholded, f)

There are 62 symptom-drug pairs that are found in the top list of drug candidates in at least 5 of the 10 runs:
 {('HP:0002791', '1795'), ('HP:0000750', '1795'), ('HP:0002791', '231'), ('HP:0001328', '5359'), ('HP:0001290', '5359'), ('HP:0003707', '231'), ('HP:0002093', '1795'), ('HP:0001270', '1795'), ('HP:0003307', '1795'), ('HP:0001252', '269'), ('HP:0001256', '1795'), ('HP:0003323', '5359'), ('HP:0001635', '231'), ('HP:0100543', '5359'), ('HP:0003115', '231'), ('HP:0002515', '5359'), ('HP:0003202', '1576'), ('HP:0002650', '5359'), ('HP:0001263', '1795'), ('HP:0011675', '1576'), ('HP:0001328', '269'), ('HP:0001371', '269'), ('HP:0003391', '269'), ('HP:0001638', '1576'), ('HP:0001371', '1576'), ('HP:0001290', '269'), ('HP:0003323', '1576'), ('HP:0001252', '1795'), ('HP:0002515', '269'), ('HP:0003701', '5359'), ('HP:0002650', '269'), ('HP:0001644', '1576'), ('HP:0008981', '1576'), ('HP:0001265', '269'), ('HP:0003236', '1576'), ('HP:0001263', '269'), ('HP:0001328', '1795'), ('HP:0003560', '1576'), ('HP:0001252', '5359'), ('HP:0003391', '1795'), ('HP:0001290', '1795'), ('HP:0001371', '1795'), ('HP:0002791', '269'), ('HP:0003701', '269'), ('HP:0001256', '269'), ('HP:0001638', '231'), ('HP:0003701', '1576'), ('HP:0002515', '1795'), ('HP:0001644', '1795'), ('HP:0000750', '269'), ('HP:0002650', '1795'), ('HP:0100543', '1795'), ('HP:0001644', '231'), ('HP:0001265', '1795'), ('HP:0001270', '269'), ('HP:0003307', '269'), ('HP:0003115', '1576'), ('HP:0008981', '231'), ('HP:0003236', '231'), ('HP:0003307', '1576'), ('HP:0003560', '231'), ('HP:0003701', '1795')}

# Symptoms related to DMD

In [56]:
edges = pd.read_csv(f'output/{disease_prefix}/indexed_edges_{dataset_nr}{suffix}.csv')
edges

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,has affected feature,HGNC:2928,DMD,4,6674,0
1,ClinVarVariant:526054,NM_004006.2(DMD):c.10224-175_10230del,10,10313,causes condition,MONDO:0010679,Duchenne muscular dystrophy,2,2191,1
2,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-000322-2,tnnc2,4,2320,2
3,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,in orthology relationship with,ENSEMBL:ENSGALG00000013537,ENSEMBL:ENSGALG00000013537,4,3734,3
4,ZFIN:ZDB-GENE-030826-16,tpm3,4,7425,interacts with,ZFIN:ZDB-GENE-040718-80,tnni2a.3,4,2851,2
...,...,...,...,...,...,...,...,...,...,...
96372,2293,propantheline,3,8037,targets,P11229,Muscarinic acetylcholine receptor M1,5,1258,14
96373,2767,troglitazone,3,10783,targets,P18031,Tyrosine-protein phosphatase non-receptor type 1,5,7624,14
96374,24,phenylbutanoic acid,3,3568,targets,Q92769,Histone deacetylase 2,5,6595,14
96375,2337,quetiapine,3,5478,targets,P11229,Muscarinic acetylcholine receptor M1,5,1258,14
96376,ClinVarVariant:455836,ClinVarVariant:455836,10,8555,causes condition,MONDO:0010679,Duchenne muscular dystrophy,2,2191,1

In [57]:
if dataset_nr == 1:
    pheno_rel = 'has phenotype'
else:
    pheno_rel = 'associated with phenotype'
    
_, relation_labels = pd.factorize(edges['relation'])

if disease_prefix == 'dmd':
    disease_ID = 'MONDO:0010679'
elif disease_prefix == 'hd':
    disease_ID = 'MONDO:0007739'
    
relation_index = list(relation_labels).index(pheno_rel)

symptoms = edges[(edges['head'] == disease_ID) & (edges['type'] == relation_index)]

print(f'A total of {symptoms.shape[0]} symptoms found that are associated with {disease_ID}')
symptoms

A total of 28 symptoms found that are associated with MONDO:0010679

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
8412,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003307,Hyperlordosis,8,9376,8
8413,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003560,Muscular dystrophy,8,3375,8
8414,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003236,Elevated circulating creatine kinase concentra...,8,2237,8
8415,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0002515,Waddling gait,8,2634,8
8416,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001328,Specific learning disability,8,8846,8
8417,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0008981,Calf muscle hypertrophy,8,5721,8
8418,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0002093,Respiratory insufficiency,8,5506,8
8419,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001265,Hyporeflexia,8,2685,8
8420,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0002791,Hypoventilation,8,9060,8
8422,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0000750,Delayed speech and language development,8,8740,8
8423,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003323,Progressive muscle weakness,8,9754,8
8424,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0002650,Scoliosis,8,2891,8
8425,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001371,Flexion contracture,8,7489,8
8426,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003202,Skeletal muscle atrophy,8,11021,8
8427,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003391,Gowers sign,8,8615,8
8428,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0100543,Cognitive impairment,8,8684,8
8429,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0011675,Arrhythmia,8,6805,8
8430,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003701,Proximal muscle weakness,8,9259,8
8431,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001290,Generalized hypotonia,8,4545,8
8433,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001270,Motor delay,8,6682,8
8434,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001638,Cardiomyopathy,8,3949,8
8435,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001256,"Intellectual disability, mild",8,6880,8
8436,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001635,Congestive heart failure,8,2841,8
8437,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001644,Dilated cardiomyopathy,8,7870,8
8438,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001263,Global developmental delay,8,7839,8
8439,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0001252,Hypotonia,8,9897,8
8440,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003115,Abnormal EKG,8,6568,8
8441,MONDO:0010679,Duchenne muscular dystrophy,2,2191,associated with phenotype,HP:0003707,Calf muscle pseudohypertrophy,8,10946,8

In [58]:
symptoms_df = symptoms[['tail', 'label_tail']]
symptoms_df = symptoms_df.rename(columns={'tail': 'Symptom ID', 'label_tail': 'Symptom'})
symptoms_df.to_csv(f'{curr_output_dir}/{disease_prefix}relatedsymptoms.csv', index=False)

# Check overlap between each model

In [59]:
nodes = pd.read_csv(f'output/{disease_prefix}/indexed_nodes_{dataset_nr}.csv')
nodes.drop('index_id', axis=1, inplace=True)
nodes['semantic'] = nodes['semantic'].astype('category')
nodes

,id,semantic,label,semantic_id
0,ZP:0003032,phenotype,"extension quality, abnormal",8
1,MP:0011749,phenotype,perivascular fibrosis,8
2,ClinVarVariant:568924,variant,NM_004006.2(DMD):c.7247T>A (p.Leu2416Ter),10
3,MP:0002551,phenotype,abnormal blood coagulation,8
4,RGD:1305759,gene,Pxn,4
...,...,...,...,...
11062,ClinVarVariant:662286,variant,NC_000023.11:g.(?_32614293)_(32651077_?)del,10
11063,MGI:1919517,gene,Lrrc8e,4
11064,ZFIN:ZDB-GENE-030131-2040,gene,actn3b,4
11065,ZP:0005918,phenotype,"brain vasculature broken, abnormal",8
11066,ZP:0021002,phenotype,"sarcomere myotome spatial pattern, abnormal",8

In [60]:
if dataset_nr == 1:
    drug_semantic = 'DRUG'
else:
    drug_semantic = 'drug'

nodes[nodes['semantic'] == drug_semantic]

         id semantic          label  semantic_id
41     3025     drug  bietamiverine            3
135    1500     drug   isopropamide            3
148    3408     drug    oxiconazole            3
193    2612     drug    sapropterin            3
238     897     drug      diltiazem            3
...     ...      ...            ...          ...
10890  1683     drug      menadione            3
10904   956     drug        doxepin            3
10941  4191     drug   fesoterodine            3
10959  2705     drug    tolterodine            3
11061   749     drug      cyclizine            3

[293 rows x 4 columns]

In [61]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output', disease_prefix)

overlapping_pairs = []

for setting in all_settings:
    dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {setting["dataset_nr"]} exists and will be loaded: {dataset_output_dir}')
        
        with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}.pkl', 'rb') as f:
            loaded_list = pickle.load(f)
            overlapping_pairs.append(loaded_list)
            
            pair_dict_list = []
            for pair in loaded_list:
                symptom_id, drug_id = pair
                
                symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
                
                drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
                pair_dict_list.append({'Drug': drug_name, 'Symptom ID': symptom_id, 'Symptom': symptom_name})
                
            overlapping_all_runs_df = pd.DataFrame(pair_dict_list)
            overlapping_all_runs_df.to_csv(f'{dataset_output_dir}/symptom_drug_pairs_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}.csv', index=False)

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g1_e2v
Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\dmd\g2_e2v

In [62]:
dataset1_emb_overlap = overlapping_pairs[0].intersection(overlapping_pairs[1])
for pair in dataset1_emb_overlap:
    symptom_id, drug_id = pair
    symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
    drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
    print(drug_name, 'treats', symptom_name)

aprindine treats Abnormal EKG
aprindine treats Cardiomyopathy