# Import Libraries

In [28]:
import os
import pickle
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics import classification_report

# Set Parameters

In [29]:
dataset_nr = 1
assert dataset_nr == 1 or 2

embedding_method = 'e2v'
assert embedding_method == 'e2v' or 'm2v'

# Additional experiments
NO_GENE_PRODUCTS = 'no gene products'
SINGLE_RELATION_TYPE = 'only one relation type'
RANDOM_FEATURES = 'random node embedding values'
concept_changes = None  # set to None when no conceptual changes are wanted

if concept_changes:
    concept_changes_str = concept_changes
else:
    concept_changes_str = ''
    
if concept_changes == NO_GENE_PRODUCTS:
    suffix = '_nogeneprods'
elif concept_changes == SINGLE_RELATION_TYPE:
    suffix = '_singlerel'
elif concept_changes == RANDOM_FEATURES:
    suffix = '_randomfeat'
else:
    suffix = ''

seeded_emb = False

if seeded_emb:
    fixed_emb = '_seeded'
else:
    fixed_emb = ''
    
if seeded_emb:
    title_seeded = ' with fixed node embeddings'
else:
    title_seeded = ''

# Get Result Paths

In [30]:
curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output')
dataset_output_dir = os.path.join(curr_output_dir, f'g{dataset_nr}_{embedding_method}{fixed_emb}{suffix}')

if not os.path.exists(dataset_output_dir):
    print('First, run the edge2vec embedding script. Then, run this script.')
else:
    print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {dataset_output_dir}')
    
run_folders_list = []
for item in os.listdir(dataset_output_dir):
    curr_path = os.path.join(dataset_output_dir, item)
    if os.path.isdir(curr_path) and 'run' in item:
        run_folders_list.append(item)

print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

run_folders_paths = []
pred_folders_paths = []
for run_folder in run_folders_list:
    run_path = os.path.join(dataset_output_dir, run_folder)
    run_folders_paths.append(run_path)
    pred_run_path = os.path.join(run_path, 'pred')
    pred_folders_paths.append(pred_run_path)
    print(pred_run_path)

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v
A total of 10 runs will be included in the analysis.
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_001\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_002\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_003\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_004\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_005\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_006\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_007\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_008\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_009\pred
c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v\run_010\pred

In [31]:
auc_scores_all_runs = []
auc_loss_scores_all_runs = []

for run_name, pred_folder in zip(run_folders_list, pred_folders_paths):
    with open(f'{pred_folder}/performance_scores_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_info = pickle.load(f)
        
    keys = ['AUC Train', 'AUC Validation', 'AUC Test']
    for key in keys:
        auc_scores = loaded_info[key]
        for index, auc_score in enumerate(auc_scores):
            auc_scores_per_run = {'run': run_name, 'name': key, 'iteration': index, 'score': auc_score}
            auc_scores_all_runs.append(auc_scores_per_run)
            auc_loss_scores_all_runs.append(auc_scores_per_run)

    loss_scores = loaded_info['Loss']
    for index, loss_score in enumerate(loss_scores):
        formatted_loss_score = float(np.log10(loss_score))
        loss_scores_per_run = {'run': run_name, 'name': 'Cross-Entropy Loss', 'iteration': index, 'score': formatted_loss_score}
        auc_loss_scores_all_runs.append(loss_scores_per_run)

# Plot ROC Curves, AUC-ROC Scores and F1 Scores for Each Model

## ROC Curves

In [32]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output')

final_test_auc_roc_scores_all_runs_all_models = []
roc_curve_all_runs_all_models = []
f1_scores_all_runs_all_models = []

for setting in all_settings:
    curr_dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(curr_dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {dataset_nr} exists and will be loaded: {curr_dataset_output_dir}')
            
        run_folders_list = []
        for item in os.listdir(curr_dataset_output_dir):
            curr_path = os.path.join(curr_dataset_output_dir, item)
            if os.path.isdir(curr_path) and 'run' in item:
                run_folders_list.append(item)

        print(f'A total of {len(run_folders_list)} runs will be included in the analysis.')

        run_folders_paths = []
        curr_pred_folders_paths = []
        for run_folder in run_folders_list:
            run_path = os.path.join(curr_dataset_output_dir, run_folder)
            run_folders_paths.append(run_path)
            pred_run_path = os.path.join(run_path, 'pred')
            curr_pred_folders_paths.append(pred_run_path)
            
        for run_name, pred_folder in zip(run_folders_list, curr_pred_folders_paths):
            with open(f'{pred_folder}/performance_scores_{setting["dataset_nr"]}_{setting["embedding_method"]}.pkl', 'rb') as f:
                loaded_info = pickle.load(f)

            auc_roc_score = loaded_info['ROC AUC Score']
            formatted_auc_roc_score = float(auc_roc_score)
            auc_roc_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                        'ROC AUC Score': formatted_auc_roc_score}
            final_test_auc_roc_scores_all_runs_all_models.append(auc_roc_score_per_run)

            roc_fpr_scores = loaded_info['ROC FPR']
            roc_tpr_scores = loaded_info['ROC TPR']
            
            for fpr, tpr in zip(roc_fpr_scores, roc_tpr_scores):
                auc_per_threshold_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}',
                                             'ROC FPR': fpr, 'ROC TPR': tpr}
                roc_curve_all_runs_all_models.append(auc_per_threshold_per_run)

            f1_score = loaded_info['F1 Score']
            formatted_f1_score = float(f1_score)
            f1_score_per_run = {'Model': f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}', 
                                'F1 Score': formatted_f1_score}
            f1_scores_all_runs_all_models.append(f1_score_per_run)

            print(f'F1-Score in the test set of dataset {setting["dataset_nr"]} and method {setting["embedding_method"]}:', f1_score)
            print(classification_report(loaded_info['True Labels'], loaded_info['Predicted Labels']))

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v
A total of 10 runs will be included in the analysis.
F1-Score in the test set of dataset 1 and method e2v: 0.948117778606038
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.92      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9477746909551954
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.92      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9509774660498433
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.96      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.93      0.93      0.93     40428
weighted avg       0.94      0.93      0.94     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9474076837001119
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.92      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9479351004973641
              precision    recall  f1-score   support

           0       0.89      0.90      0.90     13476
           1       0.95      0.94      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.92      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.949502093997208
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9494456349576074
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.9495732548171891
              precision    recall  f1-score   support

           0       0.89      0.91      0.90     13476
           1       0.95      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.93     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.948945595324511
              precision    recall  f1-score   support

           0       0.89      0.90      0.90     13476
           1       0.95      0.95      0.95     26952

    accuracy                           0.93     40428
   macro avg       0.92      0.93      0.92     40428
weighted avg       0.93      0.93      0.93     40428

F1-Score in the test set of dataset 1 and method e2v: 0.34997092756372983
              precision    recall  f1-score   support

           0       0.39      1.00      0.56     13476
           1       1.00      0.21      0.35     26952

    accuracy                           0.47     40428
   macro avg       0.69      0.61      0.45     40428
weighted avg       0.80      0.47      0.42     40428

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g2_e2v
A total of 10 runs will be included in the analysis.
F1-Score in the test set of dataset 2 and method e2v: 0.8824713913854919
              precision    recall  f1-score   support

           0       0.97      0.49      0.65     13581
           1       0.79      0.99      0.88     27162

    accuracy                           0.82     40743
   macro avg       0.88      0.74      0.77     40743
weighted avg       0.85      0.82      0.80     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8969130652427832
              precision    recall  f1-score   support

           0       0.96      0.57      0.71     13581
           1       0.82      0.99      0.90     27162

    accuracy                           0.85     40743
   macro avg       0.89      0.78      0.81     40743
weighted avg       0.87      0.85      0.84     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8771262855193256
              precision    recall  f1-score   support

           0       0.97      0.46      0.62     13581
           1       0.78      0.99      0.88     27162

    accuracy                           0.81     40743
   macro avg       0.88      0.72      0.75     40743
weighted avg       0.85      0.81      0.79     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8821787846569068
              precision    recall  f1-score   support

           0       0.97      0.48      0.65     13581
           1       0.79      0.99      0.88     27162

    accuracy                           0.82     40743
   macro avg       0.88      0.74      0.76     40743
weighted avg       0.85      0.82      0.80     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8785396753024702
              precision    recall  f1-score   support

           0       0.97      0.46      0.63     13581
           1       0.79      0.99      0.88     27162

    accuracy                           0.82     40743
   macro avg       0.88      0.73      0.75     40743
weighted avg       0.85      0.82      0.80     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8833229518408027
              precision    recall  f1-score   support

           0       0.97      0.49      0.65     13581
           1       0.80      0.99      0.88     27162

    accuracy                           0.83     40743
   macro avg       0.88      0.74      0.77     40743
weighted avg       0.85      0.83      0.81     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8794835007173603
              precision    recall  f1-score   support

           0       0.97      0.47      0.63     13581
           1       0.79      0.99      0.88     27162

    accuracy                           0.82     40743
   macro avg       0.88      0.73      0.76     40743
weighted avg       0.85      0.82      0.80     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8743926928807412
              precision    recall  f1-score   support

           0       0.97      0.44      0.61     13581
           1       0.78      0.99      0.87     27162

    accuracy                           0.81     40743
   macro avg       0.88      0.72      0.74     40743
weighted avg       0.84      0.81      0.79     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8844356253792289
              precision    recall  f1-score   support

           0       0.97      0.50      0.66     13581
           1       0.80      0.99      0.88     27162

    accuracy                           0.83     40743
   macro avg       0.88      0.74      0.77     40743
weighted avg       0.86      0.83      0.81     40743

F1-Score in the test set of dataset 2 and method e2v: 0.8897343434677607
              precision    recall  f1-score   support

           0       0.96      0.53      0.68     13581
           1       0.81      0.99      0.89     27162

    accuracy                           0.84     40743
   macro avg       0.89      0.76      0.79     40743
weighted avg       0.86      0.84      0.82     40743

In [33]:
roc_curve_all_runs_all_models = pd.DataFrame(roc_curve_all_runs_all_models)
roc_curve_all_runs_all_models

        Model   ROC FPR   ROC TPR
0      g1_e2v  0.000000  0.000000
1      g1_e2v  0.000000  0.000742
2      g1_e2v  0.000000  0.001187
3      g1_e2v  0.000000  0.001558
4      g1_e2v  0.000000  0.001707
...       ...       ...       ...
74045  g2_e2v  0.967675  0.999853
74046  g2_e2v  0.967675  0.999926
74047  g2_e2v  0.993668  0.999926
74048  g2_e2v  0.993668  1.000000
74049  g2_e2v  1.000000  1.000000

[74050 rows x 3 columns]

In [34]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'ROC TPR/ROC FPR Distribution over Each Run for Each Model')
sns.scatterplot(data=roc_curve_all_runs_all_models, x="ROC FPR", y="ROC TPR", hue="Model", s=1)
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.legend(markerscale=10)

fig.savefig(f'{curr_output_dir}/roc_curves.png', bbox_inches='tight')
fig.clear()

## F1 Scores

In [35]:
f1_scores_all_runs_all_models = pd.DataFrame(f1_scores_all_runs_all_models)
f1_scores_all_runs_all_models

     Model  F1 Score
0   g1_e2v  0.948118
1   g1_e2v  0.947775
2   g1_e2v  0.950977
3   g1_e2v  0.947408
4   g1_e2v  0.947935
5   g1_e2v  0.949502
6   g1_e2v  0.949446
7   g1_e2v  0.949573
8   g1_e2v  0.948946
9   g1_e2v  0.349971
10  g2_e2v  0.882471
11  g2_e2v  0.896913
12  g2_e2v  0.877126
13  g2_e2v  0.882179
14  g2_e2v  0.878540
15  g2_e2v  0.883323
16  g2_e2v  0.879484
17  g2_e2v  0.874393
18  g2_e2v  0.884436
19  g2_e2v  0.889734

In [36]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'F1 Scores Overview for Each Model')
sns.barplot(f1_scores_all_runs_all_models, x="Model", y="F1 Score", errorbar="sd", color='cornflowerblue')
ax.bar_label(ax.containers[0], fontsize=10, padding=5)
ax.set_xlabel('Model Variant')
ax.set_ylabel('F1 Score')

fig.savefig(f'{curr_output_dir}/f1_scores.png', bbox_inches='tight')
fig.clear()

## Final AUC-ROC Scores

In [37]:
final_test_auc_roc_scores_all_runs_all_models = pd.DataFrame(final_test_auc_roc_scores_all_runs_all_models)
final_test_auc_roc_scores_all_runs_all_models

     Model  ROC AUC Score
0   g1_e2v       0.962807
1   g1_e2v       0.962788
2   g1_e2v       0.962705
3   g1_e2v       0.960585
4   g1_e2v       0.962212
5   g1_e2v       0.964703
6   g1_e2v       0.964228
7   g1_e2v       0.962451
8   g1_e2v       0.963292
9   g1_e2v       0.961477
10  g2_e2v       0.972327
11  g2_e2v       0.971830
12  g2_e2v       0.974140
13  g2_e2v       0.970261
14  g2_e2v       0.972673
15  g2_e2v       0.970987
16  g2_e2v       0.969909
17  g2_e2v       0.971940
18  g2_e2v       0.970782
19  g2_e2v       0.971444

In [38]:
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title(f'AUC-ROC Scores Overview for Each Model')
sns.barplot(final_test_auc_roc_scores_all_runs_all_models, x="Model", y="ROC AUC Score", errorbar="sd")
ax.bar_label(ax.containers[0], fontsize=10, padding=10)
ax.set_ylim(0.85,1) # 0.85, 1
ax.set_xlabel('Model Variant')
ax.set_ylabel('AUC-ROC Score')

fig.savefig(f'{curr_output_dir}/auc_roc_scores.png', bbox_inches='tight')
fig.clear()

# Plot Training Curve

In [39]:
auc_scores_all_runs = pd.DataFrame(auc_scores_all_runs)
auc_scores_all_runs

          run       name  iteration     score
0     run_001  AUC Train          0  0.942053
1     run_001  AUC Train          1  0.934088
2     run_001  AUC Train          2  0.917342
3     run_001  AUC Train          3  0.896569
4     run_001  AUC Train          4  0.878651
...       ...        ...        ...       ...
5965  run_010   AUC Test        194  0.961133
5966  run_010   AUC Test        195  0.961106
5967  run_010   AUC Test        196  0.961152
5968  run_010   AUC Test        197  0.961273
5969  run_010   AUC Test        198  0.961386

[5970 rows x 4 columns]

In [40]:
auc_loss_scores_all_runs = pd.DataFrame(auc_loss_scores_all_runs)
auc_loss_scores_all_runs

          run                name  iteration     score
0     run_001           AUC Train          0  0.942053
1     run_001           AUC Train          1  0.934088
2     run_001           AUC Train          2  0.917342
3     run_001           AUC Train          3  0.896569
4     run_001           AUC Train          4  0.878651
...       ...                 ...        ...       ...
7955  run_010  Cross-Entropy Loss        194 -0.575803
7956  run_010  Cross-Entropy Loss        195 -0.575903
7957  run_010  Cross-Entropy Loss        196 -0.576825
7958  run_010  Cross-Entropy Loss        197 -0.575204
7959  run_010  Cross-Entropy Loss        198 -0.576769

[7960 rows x 4 columns]

In [41]:
fig, ax = plt.subplots(figsize=(8, 8))

ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(0.8,1) # 0.85, 1
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC Score')

print(dataset_output_dir)
fig.savefig(f'{dataset_output_dir}/training_curve.png', bbox_inches='tight')
fig.clear()

c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v

In [42]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Training curve on dataset {dataset_nr} {concept_changes_str}')
sns.lineplot(data=auc_loss_scores_all_runs, x='iteration', y='score', hue='name')
ax.set_ylim(top=1)
ax.set_xlabel('Iteration')
ax.set_ylabel('AUC-ROC/log10(Loss)')

fig.savefig(f'{dataset_output_dir}/training_curve_with_loss.png', bbox_inches='tight')
fig.clear()

# Similarity between top scoring symptom-drug pairs

In [43]:
drug_symptom_pairs_per_run = []

for index, pred_path in enumerate(pred_folders_paths):
    with open(f'{pred_path}/candidates_per_symptom_{dataset_nr}_{embedding_method}{suffix}.pkl', 'rb') as f:
        loaded_list = pickle.load(f)
        
        drug_symptom_pairs = []
        
        for _, row in loaded_list.iterrows():
            symptom_id = row['Symptom']
            candidates = row['Candidates']
            
            for candidate in candidates:
                drug_symptom_pairs.append(tuple([symptom_id, candidate]))
                
        total_drug_symptom_pairs = len(drug_symptom_pairs)
    
    drug_symptom_pairs_per_run.append(drug_symptom_pairs)

In [44]:
similarity_matrix = {}
ratios_non_diagonals = []

for index1, pairs1 in enumerate(drug_symptom_pairs_per_run):
    
    similarities = {}
    
    for index2, pairs2 in enumerate(drug_symptom_pairs_per_run):
        overlap = set([tuple(sorted(ele)) for ele in pairs1]) & set([tuple(sorted(ele)) for ele in pairs2])
        ratio_overlap = len(overlap) / total_drug_symptom_pairs * 100
        
        similarities[f'run {index2+1}'] = ratio_overlap
        
        if index1 != index2:
            ratios_non_diagonals.append(ratio_overlap)
        
    similarity_matrix[f'run {index1+1}'] = similarities
    
similarity_matrix_df = pd.DataFrame(similarity_matrix)
similarity_matrix_df

,run 1,run 2,run 3,run 4,run 5,run 6,run 7,run 8,run 9,run 10
run 1,100.000000,31.034483,23.563218,51.724138,39.080460,18.390805,54.022989,11.494253,34.482759,32.758621
run 2,31.034483,100.000000,26.436782,37.931034,21.264368,21.264368,55.172414,13.793103,22.988506,11.494253
run 3,23.563218,26.436782,100.000000,26.436782,24.712644,11.494253,32.183908,7.471264,18.390805,16.091954
run 4,51.724138,37.931034,26.436782,100.000000,37.356322,17.241379,53.448276,13.793103,35.057471,29.885057
run 5,39.080460,21.264368,24.712644,37.356322,100.000000,3.448276,45.977011,23.563218,36.781609,32.183908
run 6,18.390805,21.264368,11.494253,17.241379,3.448276,100.000000,25.287356,16.091954,22.413793,4.022989
run 7,54.022989,55.172414,32.183908,53.448276,45.977011,25.287356,100.000000,18.965517,35.057471,33.333333
run 8,11.494253,13.793103,7.471264,13.793103,23.563218,16.091954,18.965517,100.000000,30.459770,5.747126
run 9,34.482759,22.988506,18.390805,35.057471,36.781609,22.413793,35.057471,30.459770,100.000000,24.712644
run 10,32.758621,11.494253,16.091954,29.885057,32.183908,4.022989,33.333333,5.747126,24.712644,100.000000

In [45]:
mean_overlap_ratio = np.mean(ratios_non_diagonals)
median_overlap_ratio = np.median(ratios_non_diagonals)
print('Mean:', mean_overlap_ratio)
print('Median:', median_overlap_ratio)

Mean: 26.411238825031923
Median: 24.71264367816092

In [46]:
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title(f'Overlap ratio (Mean: {round(mean_overlap_ratio, 2)}, Median: {round(median_overlap_ratio, 2)}) between list of predicted symptom-drug pairs per run on dataset {dataset_nr} {concept_changes_str}')
sns.heatmap(similarity_matrix_df, annot=True, fmt='.1f', linewidths=0.5, ax=ax, cmap='RdYlGn')
ax.collections[0].set_clim(0,100)

fig.savefig(f'{dataset_output_dir}/overlap_between_runs.png', bbox_inches='tight')
fig.clear()

In [47]:
for i in range(0, len(drug_symptom_pairs_per_run)):
    if i == 0:
        overlapping_pairs_all_runs = set(drug_symptom_pairs_per_run[i])
    else:
        overlapping_pairs_all_runs = overlapping_pairs_all_runs & set(drug_symptom_pairs_per_run[i])
            
print(f'There are {len(overlapping_pairs_all_runs)} symptom-drug pairs that are found in the top list of drug candidates in {len(drug_symptom_pairs_per_run)} runs: \n {overlapping_pairs_all_runs}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{dataset_nr}_{embedding_method}{fixed_emb}.pkl', 'wb') as f:
    pickle.dump(overlapping_pairs_all_runs, f)

There are 1 symptom-drug pairs that are found in the top list of drug candidates in 10 runs:
 {('HP:0002067', '578')}

In [48]:
same_drug_symptom_pairs_thresholded = set()

threshold = 0.5
total_runs = len(drug_symptom_pairs_per_run)
min_nr_runs = int(threshold * total_runs)

for i in range(0, len(drug_symptom_pairs_per_run)):
    for pair in drug_symptom_pairs_per_run[i]:
        same_pairs = 0
        for j in range(0, len(drug_symptom_pairs_per_run)):
            for pair_to_compare in drug_symptom_pairs_per_run[j]:
                if pair == pair_to_compare:
                    same_pairs += 1
                        
        #print(f'For pair {pair} from run {i}, there are {same_pairs} same pairs found in list of all runs.')
        if same_pairs >= min_nr_runs:
            same_drug_symptom_pairs_thresholded.add(pair)
            
print(f'There are {len(same_drug_symptom_pairs_thresholded)} symptom-drug pairs that are found in the top list of drug candidates in at least {min_nr_runs} of the {total_runs} runs: \n {same_drug_symptom_pairs_thresholded}')

with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_{min_nr_runs}_runs_{dataset_nr}_{embedding_method}{fixed_emb}{suffix}.pkl', 'wb') as f:
    pickle.dump(same_drug_symptom_pairs_thresholded, f)

There are 101 symptom-drug pairs that are found in the top list of drug candidates in at least 5 of the 10 runs:
 {('HP:0000738', '2123'), ('HP:0001250', '578'), ('HP:0001824', '91'), ('HP:0045082', '2123'), ('HP:0002169', '2123'), ('HP:0002300', '2123'), ('HP:0031845', '2123'), ('HP:0001288', '91'), ('HP:0000739', '1990'), ('HP:0100785', '578'), ('HP:0001336', '578'), ('HP:0030955', '578'), ('HP:0004305', '578'), ('HP:0002540', '2123'), ('HP:0000726', '578'), ('HP:0002171', '700'), ('HP:0002500', '1989'), ('HP:0001288', '578'), ('HP:0003107', '2123'), ('HP:0000722', '2123'), ('HP:0002067', '578'), ('HP:0025401', '2123'), ('HP:0002171', '91'), ('HP:0002529', '578'), ('HP:0002540', '1990'), ('HP:0001824', '700'), ('HP:0001347', '2123'), ('HP:0000496', '2123'), ('HP:0002171', '578'), ('HP:0000751', '578'), ('HP:0031843', '578'), ('HP:0004408', '578'), ('HP:0000718', '2123'), ('HP:0009088', '2123'), ('HP:0000737', '2123'), ('HP:0045082', '578'), ('HP:0007010', '2123'), ('HP:0002072', '578'), ('HP:0002063', '2123'), ('HP:0001250', '2123'), ('HP:0001332', '578'), ('HP:0002312', '2123'), ('HP:0000741', '2123'), ('HP:0002066', '2123'), ('HP:0002300', '578'), ('HP:0001268', '2123'), ('HP:0002591', '578'), ('HP:0001272', '2123'), ('HP:0010794', '2123'), ('HP:0002340', '2123'), ('HP:0031589', '578'), ('HP:0000746', '2123'), ('HP:0002355', '2123'), ('HP:0000734', '2123'), ('HP:0001262', '2123'), ('HP:0100785', '2123'), ('HP:0003107', '578'), ('HP:0000722', '578'), ('HP:0002500', '2123'), ('HP:0025401', '578'), ('HP:0030842', '578'), ('HP:0031473', '578'), ('HP:0040140', '2123'), ('HP:0002059', '2123'), ('HP:0001250', '91'), ('HP:0000718', '1990'), ('HP:0002169', '578'), ('HP:0031843', '2123'), ('HP:0031845', '578'), ('HP:0004408', '2123'), ('HP:0000713', '2123'), ('HP:0003324', '2123'), ('HP:0000737', '578'), ('HP:0007010', '578'), ('HP:0002312', '578'), ('HP:0002354', '2123'), ('HP:0002072', '2123'), ('HP:0002066', '578'), ('HP:0001332', '2123'), ('HP:0200136', '2123'), ('HP:0001336', '2123'), ('HP:0004305', '2123'), ('HP:0030955', '2123'), ('HP:0000726', '2123'), ('HP:0002340', '578'), ('HP:0010794', '578'), ('HP:0000746', '578'), ('HP:0002354', '1990'), ('HP:0001262', '578'), ('HP:0002067', '2123'), ('HP:0003487', '2123'), ('HP:0002529', '2123'), ('HP:0003487', '1990'), ('HP:0040140', '578'), ('HP:0002059', '1990'), ('HP:0000751', '2123'), ('HP:0030842', '2123'), ('HP:0009088', '578'), ('HP:0031473', '2123'), ('HP:0000718', '1989'), ('HP:0002141', '2123')}

# Symptoms related to DMD

In [49]:
edges = pd.read_csv(f'output/indexed_edges_{dataset_nr}{suffix}.csv')
edges

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
0,ZFIN:ZDB-GENE-161101-1,si:dkey-52p2.5,5,2310,in orthology relationship with,RGD:1624211,RT1-T24-3,5,7485,0
1,ENSEMBL:ENSGALG00000052686,MHCIA6,5,5463,in orthology relationship with,RGD:735037,RT1-S3,5,13801,0
2,ZFIN:ZDB-GENE-040426-1975,grb2b,5,11415,interacts with,ZFIN:ZDB-GENE-041114-105,trip10a,5,12716,1
3,RGD:68337,Htt,5,7902,in 1 to 1 orthology relationship with,ENSEMBL:ENSGALG00000015635,ENSEMBL:ENSGALG00000015635,5,487,2
4,ENSEMBL:ENSPTRG00000008480,ENSEMBL:ENSPTRG00000008480,5,1769,in 1 to 1 orthology relationship with,MGI:105922,Rpl13,5,12259,2
...,...,...,...,...,...,...,...,...,...,...
228994,ENSEMBL:ENSMODG00000039032,ENSEMBL:ENSMODG00000039032,5,5808,in orthology relationship with,ENSEMBL:ENSXETG00000034683,ENSEMBL:ENSXETG00000034683,5,12421,0
228995,ENSEMBL:ENSFCAG00000002916,ENSEMBL:ENSFCAG00000002916,5,4912,in 1 to 1 orthology relationship with,HGNC:23817,CNOT10,3,10760,2
228996,ZFIN:ZDB-GENE-030909-2,add1,5,5306,in 1 to 1 orthology relationship with,PomBase:SPBC1289.14,SPBC1289.14,4,3647,2
228997,ZFIN:ZDB-GENE-040426-1707,skp1,5,5262,interacts with,ZFIN:ZDB-GENE-120919-4,itcha,5,4802,1
228998,WormBase:WBGene00007462,ctsa-3.2,5,6806,in orthology relationship with,ENSEMBL:ENSECAG00000002350,ENSEMBL:ENSECAG00000002350,5,3944,0

In [50]:
if dataset_nr == 1:
    pheno_rel = 'has phenotype'
else:
    pheno_rel = 'associated with phenotype'
    
_, relation_labels = pd.factorize(edges['relation'])

disease_ID = 'MONDO:0007739'
relation_index = list(relation_labels).index(pheno_rel)

symptoms = edges[(edges['head'] == 'MONDO:0007739') & (edges['type'] == relation_index)]

print(f'A total of {symptoms.shape[0]} symptoms found that are associated with {disease_ID}')
symptoms

A total of 58 symptoms found that are associated with MONDO:0007739

,head,label_head,class_head,index_head,relation,tail,label_tail,class_tail,index_tail,type
7192,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0003324,Generalized muscle weakness,1,8124,5
9410,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002066,Gait ataxia,1,3041,5
11571,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0031845,Abnormal libido,1,13245,5
12822,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001824,Weight loss,1,5978,5
13946,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002171,Gliosis,1,13762,5
14480,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0031843,Bradyphrenia,1,12932,5
14483,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002340,Caudate atrophy,1,3104,5
18055,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000734,Disinhibition,1,13360,5
23525,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002591,Polyphagia,1,5425,5
25953,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000737,Irritability,1,10476,5
28803,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0100785,Insomnia,1,11292,5
29754,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000496,Abnormality of eye movement,1,13506,5
30852,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002169,Clonus,1,1783,5
36385,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001272,Cerebellar atrophy,1,10758,5
37356,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002063,Rigidity,1,7044,5
38280,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000738,Hallucinations,1,6599,5
39937,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0004408,Abnormality of the sense of smell,1,9400,5
44476,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0010794,Impaired visuospatial constructive cognition,1,895,5
47642,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002059,Cerebral atrophy,1,4287,5
48123,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000713,Agitation,1,7882,5
61253,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002354,Memory impairment,1,3348,5
62299,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001347,Hyperreflexia,1,5320,5
64115,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002067,Bradykinesia,1,5273,5
75256,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0040140,Degeneration of the striatum,1,14203,5
79837,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002529,Neuronal loss in central nervous system,1,13409,5
88390,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000739,Anxiety,1,13538,5
89430,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000726,Dementia,1,3392,5
90207,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002300,Mutism,1,13621,5
90424,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002540,Inability to walk,1,4631,5
99896,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001336,Myoclonus,1,2374,5
102958,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0004305,Involuntary movements,1,460,5
104738,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001332,Dystonia,1,12060,5
109402,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001262,Excessive daytime somnolence,1,14125,5
110527,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0003487,Babinski sign,1,12381,5
111484,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0025401,Staring gaze,1,9637,5
111614,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000722,Obsessive-compulsive behavior,1,9245,5
115215,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0003107,Abnormal circulating cholesterol concentration,1,12567,5
122780,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0030842,Choking episodes,1,4277,5
125083,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002500,Abnormal cerebral white matter morphology,1,920,5
125659,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000716,Depression,1,9128,5
131867,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0007010,Poor fine motor coordination,1,1689,5
133041,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002072,Chorea,1,4337,5
141704,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000718,Aggressive behavior,1,9247,5
143650,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0200136,Oral-pharyngeal dysphagia,1,2411,5
146977,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0031473,Hostility,1,13476,5
147779,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001288,Gait disturbance,1,11194,5
156502,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002355,Difficulty walking,1,7530,5
162269,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000746,Delusions,1,11227,5
163778,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0031589,Suicidal ideation,1,11881,5
171892,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000751,Personality changes,1,10274,5
175028,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002312,Clumsiness,1,6573,5
183836,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001268,Mental deterioration,1,11,5
192495,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0002141,Gait imbalance,1,423,5
197873,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0045082,Decreased body mass index,1,4868,5
203840,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0030955,Alcoholism,1,12736,5
209043,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0000741,Apathy,1,1483,5
223548,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0009088,Speech articulation difficulties,1,9820,5
228670,MONDO:0007739,Huntington disease,1,5230,has phenotype,HP:0001250,Seizure,1,5803,5

In [51]:
symptoms_df = symptoms[['tail', 'label_tail']]
symptoms_df = symptoms_df.rename(columns={'tail': 'Symptom ID', 'label_tail': 'Symptom'})
symptoms_df.to_csv(f'{curr_output_dir}/hdrelatedsymptoms.csv', index=False)

# Check overlap between each model

In [52]:
nodes = pd.read_csv(f'output/indexed_nodes_{dataset_nr}.csv')
nodes.drop('index_id', axis=1, inplace=True)
nodes['semantic'] = nodes['semantic'].astype('category')
nodes

,id,semantic,label,semantic_id
0,ENSEMBL:ENSMMUG00000000800,ORTH,ENSEMBL:ENSMMUG00000000800,5
1,EnsemblGenome:BAE76810,ORTH,EnsemblGenome:BAE76810,5
2,ZP:0019045,DISO,"cell projection Muller cell decreased amount, ...",1
3,ZP:0000563,DISO,"neutrophil decreased amount, abnormal",1
4,MP:0008260,DISO,abnormal autophagy,1
...,...,...,...,...
14828,ENSEMBL:ENSFCAG00000014602,ORTH,ENSEMBL:ENSFCAG00000014602,5
14829,ENSEMBL:ENSCAFG00000000567,ORTH,PABPC1,5
14830,ENSEMBL:ENSFCAG00000015049,ORTH,ENSEMBL:ENSFCAG00000015049,5
14831,ENSEMBL:ENSBTAG00000052130,ORTH,LOC512323,5
14832,WormBase:WBGene00019510,ORTH,nucl-1,5

In [53]:
if dataset_nr == 1:
    drug_semantic = 'DRUG'
else:
    drug_semantic = 'drug'

nodes[nodes['semantic'] == drug_semantic]

         id semantic                   label  semantic_id
37       90     DRUG               adenosine            2
38       91     DRUG  adenosine triphosphate            2
48      114     DRUG              alfentanil            2
57      143     DRUG               alvimopan            2
65      176     DRUG              amiodarone            2
...     ...      ...                     ...          ...
2617   5389     DRUG               tucatinib            2
2625   5406     DRUG             oliceridine            2
2644   5442     DRUG             trilaciclib            2
2660   5460     DRUG             samidorphan            2
11944  5210     DRUG               olmutinib            2

[215 rows x 4 columns]

In [54]:
all_settings = [
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 1},
    {'embedding_method': 'e2v',
     'fixed_emb': '',
     'dataset_nr': 2}
]

curr_working_dir = os.getcwd()
curr_output_dir = os.path.join(curr_working_dir, 'output')

overlapping_pairs = []

for setting in all_settings:
    dataset_output_dir = os.path.join(curr_output_dir, f'g{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}')

    if not os.path.exists(dataset_output_dir):
        print('First, run the edge2vec embedding script. Then, run this script.')
    else:
        print(f'Output folder for dataset {setting["dataset_nr"]} exists and will be loaded: {dataset_output_dir}')
        
        with open(f'{dataset_output_dir}/symptom_drug_pair_overlapping_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}{setting["fixed_emb"]}.pkl', 'rb') as f:
            loaded_list = pickle.load(f)
            overlapping_pairs.append(loaded_list)
            
            pair_dict_list = []
            for pair in loaded_list:
                symptom_id, drug_id = pair
                
                symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
                
                drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
                pair_dict_list.append({'Drug': drug_name, 'Symptom ID': symptom_id, 'Symptom': symptom_name})
                
            overlapping_all_runs_df = pd.DataFrame(pair_dict_list)
            overlapping_all_runs_df.to_csv(f'{dataset_output_dir}/symptom_drug_pairs_all_runs_{setting["dataset_nr"]}_{setting["embedding_method"]}.csv', index=False)

Output folder for dataset 1 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g1_e2v
Output folder for dataset 2 exists and will be loaded: c:\Users\rosa-\Google Drive\Msc_Bioinformatics\thesis\XAIFO-ThesisProject\output\g2_e2v

In [55]:
dataset1_emb_overlap = overlapping_pairs[0].intersection(overlapping_pairs[1])
for pair in dataset1_emb_overlap:
    symptom_id, drug_id = pair
    symptom_name = nodes.loc[nodes['id'] == symptom_id]['label'].iloc[0]
    drug_name = nodes.loc[nodes['id'] == drug_id]['label'].iloc[0]
    print(drug_name, 'treats', symptom_name)